version: "3"

tasks:
  build:
    desc: Build the arc binary
    vars:
      VERSION:
        sh: git describe --tags --always --dirty 2>/dev/null || echo dev
      COMMIT:
        sh: git rev-parse --short HEAD 2>/dev/null || echo unknown
      DATE:
        sh: date -u +%Y-%m-%dT%H:%M:%SZ
    cmds:
      - go build -ldflags "-X main.version={{.VERSION}} -X main.commit={{.COMMIT}} -X main.buildDate={{.DATE}}" -o bin/arc ./cmd/arc
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
    generates:
      - bin/arc
