version: "3"

tasks:
  generate:
    desc: Generate protobuf Go code
    cmds:
      - buf generate
    sources:
      - api/proto/**/*.proto
      - buf.gen.yaml
    generates:
      - api/arc/node/v1/*.pb.go
  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...
  fmt:
    desc: Format Go files in-place
    cmds:
      - git ls-files "*.go" | xargs gofmt -w
  build:
    desc: Build the arc binary and Docker image
    deps:
      - build:bin
      - build:docker
  build:bin:
    desc: Build the arc binary
    deps: [generate]
    vars:
      VERSION:
        sh: git describe --tags --always --dirty 2>/dev/null || echo dev
      COMMIT:
        sh: git rev-parse --short HEAD 2>/dev/null || echo unknown
      DATE:
        sh: date -u +%Y-%m-%dT%H:%M:%SZ
    cmds:
      - go build -ldflags "-X main.version={{.VERSION}} -X main.commit={{.COMMIT}} -X main.buildDate={{.DATE}}" -o bin/arc ./cmd/arc
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
    generates:
      - bin/arc
  build:docker:
    desc: Build the Docker image
    vars:
      VERSION:
        sh: git describe --tags --always --dirty 2>/dev/null || echo dev
    cmds:
      - docker build -t gezibash/arc:{{.VERSION}} -t gezibash/arc:latest .
