// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: arc/relay/v1/relay.proto

package relayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReceiptStatus int32

const (
	ReceiptStatus_RECEIPT_STATUS_UNSPECIFIED ReceiptStatus = 0
	ReceiptStatus_RECEIPT_STATUS_ACK         ReceiptStatus = 1 // Envelope accepted and routed
	ReceiptStatus_RECEIPT_STATUS_NACK        ReceiptStatus = 2 // Envelope rejected (see reason)
)

// Enum value maps for ReceiptStatus.
var (
	ReceiptStatus_name = map[int32]string{
		0: "RECEIPT_STATUS_UNSPECIFIED",
		1: "RECEIPT_STATUS_ACK",
		2: "RECEIPT_STATUS_NACK",
	}
	ReceiptStatus_value = map[string]int32{
		"RECEIPT_STATUS_UNSPECIFIED": 0,
		"RECEIPT_STATUS_ACK":         1,
		"RECEIPT_STATUS_NACK":        2,
	}
)

func (x ReceiptStatus) Enum() *ReceiptStatus {
	p := new(ReceiptStatus)
	*p = x
	return p
}

func (x ReceiptStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReceiptStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_arc_relay_v1_relay_proto_enumTypes[0].Descriptor()
}

func (ReceiptStatus) Type() protoreflect.EnumType {
	return &file_arc_relay_v1_relay_proto_enumTypes[0]
}

func (x ReceiptStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReceiptStatus.Descriptor instead.
func (ReceiptStatus) EnumDescriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{0}
}

// Envelope is the unit of transmission through the relay.
// Content-addressed by SHA-256 hash of (labels + payload).
//
// Routing labels live here. The payload (typically an arc.Message) may have
// its own labels for indexing — relay doesn't inspect those.
//
// Signature model:
//   - The payload (Message) is signed by the AUTHOR (content provenance)
//   - The envelope is signed by the RELAY (routing provenance)
//   - Receivers verify relay sig, then unseal and verify message sig
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content-addressed reference (SHA-256 hash). Computed by relay if empty.
	Ref []byte `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Routing labels (exact-match). Special key:
	//
	//	"to" - addressed routing to @name (requires RegisterNameFrame)
	//
	// All other keys use standard label matching. Capabilities are just labels:
	//
	//	{"capability": "storage"} - routes to subscribers with that label
	Labels map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Opaque payload, typically a serialized arc.Message. Relay does not inspect this.
	// The message inside should be signed by its author.
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Sender's public key (32 bytes Ed25519). Set by relay from authenticated connection.
	Sender []byte `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	// Relay's Ed25519 signature over (ref + labels + payload + sender).
	// Proves this envelope was handled by this relay.
	RelaySignature []byte `protobuf:"bytes,5,opt,name=relay_signature,json=relaySignature,proto3" json:"relay_signature,omitempty"`
	// Relay's public key (32 bytes Ed25519). Identifies which relay signed.
	RelayPubkey   []byte `protobuf:"bytes,6,opt,name=relay_pubkey,json=relayPubkey,proto3" json:"relay_pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetRef() []byte {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Envelope) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Envelope) GetRelaySignature() []byte {
	if x != nil {
		return x.RelaySignature
	}
	return nil
}

func (x *Envelope) GetRelayPubkey() []byte {
	if x != nil {
		return x.RelayPubkey
	}
	return nil
}

// Receipt acknowledges envelope processing by the relay.
// "Delivered" means queued in subscriber buffers, NOT processed by app.
// Signed by the relay to prove acknowledgment.
type Receipt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference of the envelope this receipt is for.
	Ref []byte `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Client-provided correlation ID, echoed back.
	Correlation string `protobuf:"bytes,2,opt,name=correlation,proto3" json:"correlation,omitempty"`
	// Receipt status.
	Status ReceiptStatus `protobuf:"varint,3,opt,name=status,proto3,enum=arc.relay.v1.ReceiptStatus" json:"status,omitempty"`
	// Number of subscriber buffers that accepted the envelope.
	Delivered int32 `protobuf:"varint,4,opt,name=delivered,proto3" json:"delivered,omitempty"`
	// Human-readable reason (for NACK).
	Reason string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	// Relay's Ed25519 signature over (ref + correlation + status + delivered + reason).
	// Proves this receipt was issued by this relay.
	RelaySignature []byte `protobuf:"bytes,6,opt,name=relay_signature,json=relaySignature,proto3" json:"relay_signature,omitempty"`
	// Relay's public key (32 bytes Ed25519). Identifies which relay signed.
	RelayPubkey   []byte `protobuf:"bytes,7,opt,name=relay_pubkey,json=relayPubkey,proto3" json:"relay_pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{1}
}

func (x *Receipt) GetRef() []byte {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Receipt) GetCorrelation() string {
	if x != nil {
		return x.Correlation
	}
	return ""
}

func (x *Receipt) GetStatus() ReceiptStatus {
	if x != nil {
		return x.Status
	}
	return ReceiptStatus_RECEIPT_STATUS_UNSPECIFIED
}

func (x *Receipt) GetDelivered() int32 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

func (x *Receipt) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Receipt) GetRelaySignature() []byte {
	if x != nil {
		return x.RelaySignature
	}
	return nil
}

func (x *Receipt) GetRelayPubkey() []byte {
	if x != nil {
		return x.RelayPubkey
	}
	return nil
}

// LabelValue carries a typed label value for discovery and state reporting.
// Envelope routing labels stay map<string, string> — these typed values are
// only used in subscriptions, discovery, and state.
type LabelValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*LabelValue_StringValue
	//	*LabelValue_IntValue
	//	*LabelValue_DoubleValue
	//	*LabelValue_BoolValue
	Value         isLabelValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelValue) Reset() {
	*x = LabelValue{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelValue) ProtoMessage() {}

func (x *LabelValue) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelValue.ProtoReflect.Descriptor instead.
func (*LabelValue) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{2}
}

func (x *LabelValue) GetValue() isLabelValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *LabelValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*LabelValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *LabelValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*LabelValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *LabelValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*LabelValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *LabelValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*LabelValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isLabelValue_Value interface {
	isLabelValue_Value()
}

type LabelValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type LabelValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type LabelValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type LabelValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*LabelValue_StringValue) isLabelValue_Value() {}

func (*LabelValue_IntValue) isLabelValue_Value() {}

func (*LabelValue_DoubleValue) isLabelValue_Value() {}

func (*LabelValue_BoolValue) isLabelValue_Value() {}

type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ClientFrame_Send
	//	*ClientFrame_Subscribe
	//	*ClientFrame_Unsubscribe
	//	*ClientFrame_RegisterName
	//	*ClientFrame_Ping
	//	*ClientFrame_Discover
	//	*ClientFrame_UpdateLabels
	//	*ClientFrame_UpdateState
	Frame         isClientFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{3}
}

func (x *ClientFrame) GetFrame() isClientFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ClientFrame) GetSend() *SendFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Send); ok {
			return x.Send
		}
	}
	return nil
}

func (x *ClientFrame) GetSubscribe() *SubscribeFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *ClientFrame) GetUnsubscribe() *UnsubscribeFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *ClientFrame) GetRegisterName() *RegisterNameFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_RegisterName); ok {
			return x.RegisterName
		}
	}
	return nil
}

func (x *ClientFrame) GetPing() *PingFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ClientFrame) GetDiscover() *DiscoverFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Discover); ok {
			return x.Discover
		}
	}
	return nil
}

func (x *ClientFrame) GetUpdateLabels() *UpdateLabelsFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_UpdateLabels); ok {
			return x.UpdateLabels
		}
	}
	return nil
}

func (x *ClientFrame) GetUpdateState() *UpdateStateFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_UpdateState); ok {
			return x.UpdateState
		}
	}
	return nil
}

type isClientFrame_Frame interface {
	isClientFrame_Frame()
}

type ClientFrame_Send struct {
	Send *SendFrame `protobuf:"bytes,1,opt,name=send,proto3,oneof"`
}

type ClientFrame_Subscribe struct {
	Subscribe *SubscribeFrame `protobuf:"bytes,2,opt,name=subscribe,proto3,oneof"`
}

type ClientFrame_Unsubscribe struct {
	Unsubscribe *UnsubscribeFrame `protobuf:"bytes,3,opt,name=unsubscribe,proto3,oneof"`
}

type ClientFrame_RegisterName struct {
	RegisterName *RegisterNameFrame `protobuf:"bytes,4,opt,name=register_name,json=registerName,proto3,oneof"`
}

type ClientFrame_Ping struct {
	Ping *PingFrame `protobuf:"bytes,5,opt,name=ping,proto3,oneof"`
}

type ClientFrame_Discover struct {
	Discover *DiscoverFrame `protobuf:"bytes,6,opt,name=discover,proto3,oneof"`
}

type ClientFrame_UpdateLabels struct {
	UpdateLabels *UpdateLabelsFrame `protobuf:"bytes,7,opt,name=update_labels,json=updateLabels,proto3,oneof"`
}

type ClientFrame_UpdateState struct {
	UpdateState *UpdateStateFrame `protobuf:"bytes,8,opt,name=update_state,json=updateState,proto3,oneof"`
}

func (*ClientFrame_Send) isClientFrame_Frame() {}

func (*ClientFrame_Subscribe) isClientFrame_Frame() {}

func (*ClientFrame_Unsubscribe) isClientFrame_Frame() {}

func (*ClientFrame_RegisterName) isClientFrame_Frame() {}

func (*ClientFrame_Ping) isClientFrame_Frame() {}

func (*ClientFrame_Discover) isClientFrame_Frame() {}

func (*ClientFrame_UpdateLabels) isClientFrame_Frame() {}

func (*ClientFrame_UpdateState) isClientFrame_Frame() {}

// SendFrame publishes an envelope through the relay.
type SendFrame struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Envelope *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// Optional correlation ID for matching receipts.
	Correlation   string `protobuf:"bytes,2,opt,name=correlation,proto3" json:"correlation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFrame) Reset() {
	*x = SendFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFrame) ProtoMessage() {}

func (x *SendFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFrame.ProtoReflect.Descriptor instead.
func (*SendFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{4}
}

func (x *SendFrame) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *SendFrame) GetCorrelation() string {
	if x != nil {
		return x.Correlation
	}
	return ""
}

// SubscribeFrame registers interest in envelopes matching labels.
// Uses exact-match semantics (no CEL, no wildcards).
type SubscribeFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subscription ID (client-generated, for unsubscribe).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Labels to match (string-only, for backward compatibility).
	// All specified labels must match exactly.
	// Empty map means "match all" (not recommended).
	Labels map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Typed labels (string, int64, double, bool). Server reads these first,
	// falling back to `labels` for keys not present here.
	// Non-string values participate in discovery/CEL only, not envelope routing.
	TypedLabels   map[string]*LabelValue `protobuf:"bytes,3,rep,name=typed_labels,json=typedLabels,proto3" json:"typed_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeFrame) Reset() {
	*x = SubscribeFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeFrame) ProtoMessage() {}

func (x *SubscribeFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeFrame.ProtoReflect.Descriptor instead.
func (*SubscribeFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeFrame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubscribeFrame) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SubscribeFrame) GetTypedLabels() map[string]*LabelValue {
	if x != nil {
		return x.TypedLabels
	}
	return nil
}

// UnsubscribeFrame removes a subscription.
type UnsubscribeFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subscription ID from SubscribeFrame.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeFrame) Reset() {
	*x = UnsubscribeFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeFrame) ProtoMessage() {}

func (x *UnsubscribeFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeFrame.ProtoReflect.Descriptor instead.
func (*UnsubscribeFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{6}
}

func (x *UnsubscribeFrame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// RegisterNameFrame claims an addressed name for this connection.
// Names are prefixed with @ (e.g., "@alice").
type RegisterNameFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name to register (without @ prefix).
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNameFrame) Reset() {
	*x = RegisterNameFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNameFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNameFrame) ProtoMessage() {}

func (x *RegisterNameFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNameFrame.ProtoReflect.Descriptor instead.
func (*RegisterNameFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterNameFrame) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// PingFrame is a keepalive and latency reporter.
type PingFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Nonce []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Client's last measured round-trip latency to the relay in nanoseconds.
	// Populated by the client after measuring via ping/pong.
	// The server reads this to know the subscriber's RTT without initiating its own pings.
	MeasuredLatencyNs int64 `protobuf:"varint,2,opt,name=measured_latency_ns,json=measuredLatencyNs,proto3" json:"measured_latency_ns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PingFrame) Reset() {
	*x = PingFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingFrame) ProtoMessage() {}

func (x *PingFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingFrame.ProtoReflect.Descriptor instead.
func (*PingFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{8}
}

func (x *PingFrame) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *PingFrame) GetMeasuredLatencyNs() int64 {
	if x != nil {
		return x.MeasuredLatencyNs
	}
	return 0
}

// UpdateLabelsFrame updates subscription labels without re-subscribing.
// Used for dynamic label updates (e.g., region, tier changes).
type UpdateLabelsFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subscription ID to update.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Labels to merge into existing subscription labels (string-only, backward compat).
	// Existing keys are overwritten, new keys are added.
	Labels map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Label keys to remove. Applied after merge.
	Remove []string `protobuf:"bytes,3,rep,name=remove,proto3" json:"remove,omitempty"`
	// Typed labels to merge. Overrides string-only labels for same key.
	TypedLabels   map[string]*LabelValue `protobuf:"bytes,4,rep,name=typed_labels,json=typedLabels,proto3" json:"typed_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLabelsFrame) Reset() {
	*x = UpdateLabelsFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLabelsFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLabelsFrame) ProtoMessage() {}

func (x *UpdateLabelsFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLabelsFrame.ProtoReflect.Descriptor instead.
func (*UpdateLabelsFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateLabelsFrame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLabelsFrame) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *UpdateLabelsFrame) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

func (x *UpdateLabelsFrame) GetTypedLabels() map[string]*LabelValue {
	if x != nil {
		return x.TypedLabels
	}
	return nil
}

// UpdateStateFrame updates dynamic state (metrics, load, capacity) without
// affecting subscription labels. State is visible in discovery but gossips
// on a timer (30s) rather than immediately.
type UpdateStateFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subscription ID to update.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// State entries to set or overwrite.
	State map[string]*LabelValue `protobuf:"bytes,2,rep,name=state,proto3" json:"state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// State keys to remove.
	Remove        []string `protobuf:"bytes,3,rep,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStateFrame) Reset() {
	*x = UpdateStateFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStateFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStateFrame) ProtoMessage() {}

func (x *UpdateStateFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStateFrame.ProtoReflect.Descriptor instead.
func (*UpdateStateFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateStateFrame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStateFrame) GetState() map[string]*LabelValue {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *UpdateStateFrame) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ServerFrame_Deliver
	//	*ServerFrame_Receipt
	//	*ServerFrame_Error
	//	*ServerFrame_Pong
	//	*ServerFrame_DiscoverResult
	Frame         isServerFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{11}
}

func (x *ServerFrame) GetFrame() isServerFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ServerFrame) GetDeliver() *DeliverFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Deliver); ok {
			return x.Deliver
		}
	}
	return nil
}

func (x *ServerFrame) GetReceipt() *ReceiptFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Receipt); ok {
			return x.Receipt
		}
	}
	return nil
}

func (x *ServerFrame) GetError() *ErrorFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerFrame) GetPong() *PongFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ServerFrame) GetDiscoverResult() *DiscoverResultFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_DiscoverResult); ok {
			return x.DiscoverResult
		}
	}
	return nil
}

type isServerFrame_Frame interface {
	isServerFrame_Frame()
}

type ServerFrame_Deliver struct {
	Deliver *DeliverFrame `protobuf:"bytes,1,opt,name=deliver,proto3,oneof"`
}

type ServerFrame_Receipt struct {
	Receipt *ReceiptFrame `protobuf:"bytes,2,opt,name=receipt,proto3,oneof"`
}

type ServerFrame_Error struct {
	Error *ErrorFrame `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type ServerFrame_Pong struct {
	Pong *PongFrame `protobuf:"bytes,4,opt,name=pong,proto3,oneof"`
}

type ServerFrame_DiscoverResult struct {
	DiscoverResult *DiscoverResultFrame `protobuf:"bytes,5,opt,name=discover_result,json=discoverResult,proto3,oneof"`
}

func (*ServerFrame_Deliver) isServerFrame_Frame() {}

func (*ServerFrame_Receipt) isServerFrame_Frame() {}

func (*ServerFrame_Error) isServerFrame_Frame() {}

func (*ServerFrame_Pong) isServerFrame_Frame() {}

func (*ServerFrame_DiscoverResult) isServerFrame_Frame() {}

// DeliverFrame delivers an envelope to a subscriber.
type DeliverFrame struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Envelope *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// Which subscription matched (from SubscribeFrame.id).
	SubscriptionId string `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeliverFrame) Reset() {
	*x = DeliverFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverFrame) ProtoMessage() {}

func (x *DeliverFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverFrame.ProtoReflect.Descriptor instead.
func (*DeliverFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{12}
}

func (x *DeliverFrame) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *DeliverFrame) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

// ReceiptFrame wraps a Receipt for the stream.
type ReceiptFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *Receipt               `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiptFrame) Reset() {
	*x = ReceiptFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptFrame) ProtoMessage() {}

func (x *ReceiptFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptFrame.ProtoReflect.Descriptor instead.
func (*ReceiptFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{13}
}

func (x *ReceiptFrame) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

// ErrorFrame reports an error (subscription failed, registration failed, etc.).
type ErrorFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gRPC-compatible error code.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Machine-readable error type (e.g., "NAME_TAKEN", "INVALID_SIGNATURE").
	Detail string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	// Whether client should retry.
	Retryable bool `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	// Which request this error is for (correlation or subscription ID).
	Correlation   string `protobuf:"bytes,5,opt,name=correlation,proto3" json:"correlation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorFrame) Reset() {
	*x = ErrorFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorFrame) ProtoMessage() {}

func (x *ErrorFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorFrame.ProtoReflect.Descriptor instead.
func (*ErrorFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{14}
}

func (x *ErrorFrame) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorFrame) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorFrame) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ErrorFrame) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ErrorFrame) GetCorrelation() string {
	if x != nil {
		return x.Correlation
	}
	return ""
}

// PongFrame responds to PingFrame.
type PongFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Nonce []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Server timestamp (unix nanos).
	ServerTime    int64 `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongFrame) Reset() {
	*x = PongFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongFrame) ProtoMessage() {}

func (x *PongFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongFrame.ProtoReflect.Descriptor instead.
func (*PongFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{15}
}

func (x *PongFrame) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *PongFrame) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// DiscoverFrame requests capability discovery.
// Returns subscriptions where all filter labels are present in the subscription labels.
type DiscoverFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter labels - subscriptions must have ALL these labels.
	// Empty filter returns all subscriptions.
	Filter map[string]string `protobuf:"bytes,1,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional correlation ID for matching response.
	Correlation string `protobuf:"bytes,2,opt,name=correlation,proto3" json:"correlation,omitempty"`
	// Maximum results to return. 0 = server default (100).
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// CEL expression for discovery filtering. If set, filter is ignored and this
	// expression is evaluated against merged labels ∪ state for each subscription.
	// Example: 'capability == "blob" && capacity > 1000000000'
	Expression    string `protobuf:"bytes,4,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverFrame) Reset() {
	*x = DiscoverFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverFrame) ProtoMessage() {}

func (x *DiscoverFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverFrame.ProtoReflect.Descriptor instead.
func (*DiscoverFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{16}
}

func (x *DiscoverFrame) GetFilter() map[string]string {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *DiscoverFrame) GetCorrelation() string {
	if x != nil {
		return x.Correlation
	}
	return ""
}

func (x *DiscoverFrame) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DiscoverFrame) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

// DiscoverResultFrame contains discovery results.
type DiscoverResultFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlation ID from request, echoed back.
	Correlation string `protobuf:"bytes,1,opt,name=correlation,proto3" json:"correlation,omitempty"`
	// Matching providers.
	Providers []*ProviderInfo `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`
	// Total number of matches (may be > len(providers) if limited).
	Total int32 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	// True if more results are available.
	HasMore       bool `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResultFrame) Reset() {
	*x = DiscoverResultFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResultFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResultFrame) ProtoMessage() {}

func (x *DiscoverResultFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResultFrame.ProtoReflect.Descriptor instead.
func (*DiscoverResultFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{17}
}

func (x *DiscoverResultFrame) GetCorrelation() string {
	if x != nil {
		return x.Correlation
	}
	return ""
}

func (x *DiscoverResultFrame) GetProviders() []*ProviderInfo {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *DiscoverResultFrame) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DiscoverResultFrame) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// ProviderInfo describes a provider found by discovery.
type ProviderInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider's public key (32 bytes Ed25519).
	Pubkey []byte `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// Registered @name if any.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Full subscription labels.
	Labels map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Subscription ID that matched.
	SubscriptionId string `protobuf:"bytes,4,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	// Relay's public key this provider is connected to (for federation).
	// Empty if relay pubkey not configured.
	RelayPubkey []byte `protobuf:"bytes,5,opt,name=relay_pubkey,json=relayPubkey,proto3" json:"relay_pubkey,omitempty"`
	// Docker-style petname derived from pubkey (e.g., "clever-penguin").
	// Provides human-readable identifier when no @name is registered.
	Petname string `protobuf:"bytes,6,opt,name=petname,proto3" json:"petname,omitempty"`
	// Round-trip latency to this provider in nanoseconds (measured via ping/pong).
	// Zero if not yet measured.
	LatencyNs int64 `protobuf:"varint,7,opt,name=latency_ns,json=latencyNs,proto3" json:"latency_ns,omitempty"`
	// Last time relay received a message from this provider (unix nanos).
	LastSeenNs int64 `protobuf:"varint,8,opt,name=last_seen_ns,json=lastSeenNs,proto3" json:"last_seen_ns,omitempty"`
	// Connection age in nanoseconds (how long connected to relay).
	ConnectedNs int64 `protobuf:"varint,9,opt,name=connected_ns,json=connectedNs,proto3" json:"connected_ns,omitempty"`
	// Inter-relay latency in nanoseconds (local relay → remote relay via gossip SWIM probes).
	// Zero for local providers (same relay as the querying client).
	InterRelayLatencyNs int64 `protobuf:"varint,10,opt,name=inter_relay_latency_ns,json=interRelayLatencyNs,proto3" json:"inter_relay_latency_ns,omitempty"`
	// Typed subscription labels (superset of string labels).
	// Includes non-string values like capacity, max_obj_size.
	TypedLabels map[string]*LabelValue `protobuf:"bytes,11,rep,name=typed_labels,json=typedLabels,proto3" json:"typed_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Dynamic state (metrics, load, etc.). Gossips on timer, not on change.
	State         map[string]*LabelValue `protobuf:"bytes,12,rep,name=state,proto3" json:"state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{18}
}

func (x *ProviderInfo) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *ProviderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ProviderInfo) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *ProviderInfo) GetRelayPubkey() []byte {
	if x != nil {
		return x.RelayPubkey
	}
	return nil
}

func (x *ProviderInfo) GetPetname() string {
	if x != nil {
		return x.Petname
	}
	return ""
}

func (x *ProviderInfo) GetLatencyNs() int64 {
	if x != nil {
		return x.LatencyNs
	}
	return 0
}

func (x *ProviderInfo) GetLastSeenNs() int64 {
	if x != nil {
		return x.LastSeenNs
	}
	return 0
}

func (x *ProviderInfo) GetConnectedNs() int64 {
	if x != nil {
		return x.ConnectedNs
	}
	return 0
}

func (x *ProviderInfo) GetInterRelayLatencyNs() int64 {
	if x != nil {
		return x.InterRelayLatencyNs
	}
	return 0
}

func (x *ProviderInfo) GetTypedLabels() map[string]*LabelValue {
	if x != nil {
		return x.TypedLabels
	}
	return nil
}

func (x *ProviderInfo) GetState() map[string]*LabelValue {
	if x != nil {
		return x.State
	}
	return nil
}

type ForwardEnvelopeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The envelope to route locally on the receiving relay.
	Envelope *Envelope `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// Source relay name (for logging/tracing).
	SourceRelay   string `protobuf:"bytes,2,opt,name=source_relay,json=sourceRelay,proto3" json:"source_relay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardEnvelopeRequest) Reset() {
	*x = ForwardEnvelopeRequest{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardEnvelopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardEnvelopeRequest) ProtoMessage() {}

func (x *ForwardEnvelopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardEnvelopeRequest.ProtoReflect.Descriptor instead.
func (*ForwardEnvelopeRequest) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{19}
}

func (x *ForwardEnvelopeRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *ForwardEnvelopeRequest) GetSourceRelay() string {
	if x != nil {
		return x.SourceRelay
	}
	return ""
}

type ForwardEnvelopeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of local subscribers that accepted the envelope.
	Delivered int32 `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"`
	// NACK reason if delivered == 0.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardEnvelopeResponse) Reset() {
	*x = ForwardEnvelopeResponse{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardEnvelopeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardEnvelopeResponse) ProtoMessage() {}

func (x *ForwardEnvelopeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardEnvelopeResponse.ProtoReflect.Descriptor instead.
func (*ForwardEnvelopeResponse) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{20}
}

func (x *ForwardEnvelopeResponse) GetDelivered() int32 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

func (x *ForwardEnvelopeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GossipJoinRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Peer addresses to join (e.g., "host:port").
	Peers         []string `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipJoinRequest) Reset() {
	*x = GossipJoinRequest{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipJoinRequest) ProtoMessage() {}

func (x *GossipJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipJoinRequest.ProtoReflect.Descriptor instead.
func (*GossipJoinRequest) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{21}
}

func (x *GossipJoinRequest) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

type GossipJoinResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of peers successfully joined.
	Joined        int32 `protobuf:"varint,1,opt,name=joined,proto3" json:"joined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipJoinResponse) Reset() {
	*x = GossipJoinResponse{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipJoinResponse) ProtoMessage() {}

func (x *GossipJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipJoinResponse.ProtoReflect.Descriptor instead.
func (*GossipJoinResponse) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{22}
}

func (x *GossipJoinResponse) GetJoined() int32 {
	if x != nil {
		return x.Joined
	}
	return 0
}

type GossipMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMembersRequest) Reset() {
	*x = GossipMembersRequest{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMembersRequest) ProtoMessage() {}

func (x *GossipMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMembersRequest.ProtoReflect.Descriptor instead.
func (*GossipMembersRequest) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{23}
}

type GossipMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*GossipMember        `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMembersResponse) Reset() {
	*x = GossipMembersResponse{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMembersResponse) ProtoMessage() {}

func (x *GossipMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMembersResponse.ProtoReflect.Descriptor instead.
func (*GossipMembersResponse) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{24}
}

func (x *GossipMembersResponse) GetMembers() []*GossipMember {
	if x != nil {
		return x.Members
	}
	return nil
}

// GossipMember describes a node in the gossip cluster.
type GossipMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Gossip address (host:port).
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	// gRPC data plane address.
	GrpcAddr string `protobuf:"bytes,3,opt,name=grpc_addr,json=grpcAddr,proto3" json:"grpc_addr,omitempty"`
	// Status: alive, suspect, dead, left.
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// Node's public key.
	Pubkey []byte `protobuf:"bytes,5,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// Number of connected subscribers.
	Connections int32 `protobuf:"varint,6,opt,name=connections,proto3" json:"connections,omitempty"`
	// Uptime in nanoseconds.
	UptimeNs int64 `protobuf:"varint,7,opt,name=uptime_ns,json=uptimeNs,proto3" json:"uptime_ns,omitempty"`
	// Inter-relay latency in nanoseconds (0 for local).
	LatencyNs int64 `protobuf:"varint,8,opt,name=latency_ns,json=latencyNs,proto3" json:"latency_ns,omitempty"`
	// True if this is the relay we're querying.
	IsLocal       bool `protobuf:"varint,9,opt,name=is_local,json=isLocal,proto3" json:"is_local,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMember) Reset() {
	*x = GossipMember{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMember) ProtoMessage() {}

func (x *GossipMember) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMember.ProtoReflect.Descriptor instead.
func (*GossipMember) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{25}
}

func (x *GossipMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GossipMember) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *GossipMember) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

func (x *GossipMember) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GossipMember) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *GossipMember) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *GossipMember) GetUptimeNs() int64 {
	if x != nil {
		return x.UptimeNs
	}
	return 0
}

func (x *GossipMember) GetLatencyNs() int64 {
	if x != nil {
		return x.LatencyNs
	}
	return 0
}

func (x *GossipMember) GetIsLocal() bool {
	if x != nil {
		return x.IsLocal
	}
	return false
}

type GossipLeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipLeaveRequest) Reset() {
	*x = GossipLeaveRequest{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipLeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipLeaveRequest) ProtoMessage() {}

func (x *GossipLeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipLeaveRequest.ProtoReflect.Descriptor instead.
func (*GossipLeaveRequest) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{26}
}

type GossipLeaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipLeaveResponse) Reset() {
	*x = GossipLeaveResponse{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipLeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipLeaveResponse) ProtoMessage() {}

func (x *GossipLeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipLeaveResponse.ProtoReflect.Descriptor instead.
func (*GossipLeaveResponse) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{27}
}

var File_arc_relay_v1_relay_proto protoreflect.FileDescriptor

const file_arc_relay_v1_relay_proto_rawDesc = "" +
	"\n" +
	"\x18arc/relay/v1/relay.proto\x12\farc.relay.v1\"\x91\x02\n" +
	"\bEnvelope\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\fR\x03ref\x12:\n" +
	"\x06labels\x18\x02 \x03(\v2\".arc.relay.v1.Envelope.LabelsEntryR\x06labels\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\fR\x06sender\x12'\n" +
	"\x0frelay_signature\x18\x05 \x01(\fR\x0erelaySignature\x12!\n" +
	"\frelay_pubkey\x18\x06 \x01(\fR\vrelayPubkey\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf4\x01\n" +
	"\aReceipt\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\fR\x03ref\x12 \n" +
	"\vcorrelation\x18\x02 \x01(\tR\vcorrelation\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.arc.relay.v1.ReceiptStatusR\x06status\x12\x1c\n" +
	"\tdelivered\x18\x04 \x01(\x05R\tdelivered\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12'\n" +
	"\x0frelay_signature\x18\x06 \x01(\fR\x0erelaySignature\x12!\n" +
	"\frelay_pubkey\x18\a \x01(\fR\vrelayPubkey\"\x9f\x01\n" +
	"\n" +
	"LabelValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValueB\a\n" +
	"\x05value\"\x86\x04\n" +
	"\vClientFrame\x12-\n" +
	"\x04send\x18\x01 \x01(\v2\x17.arc.relay.v1.SendFrameH\x00R\x04send\x12<\n" +
	"\tsubscribe\x18\x02 \x01(\v2\x1c.arc.relay.v1.SubscribeFrameH\x00R\tsubscribe\x12B\n" +
	"\vunsubscribe\x18\x03 \x01(\v2\x1e.arc.relay.v1.UnsubscribeFrameH\x00R\vunsubscribe\x12F\n" +
	"\rregister_name\x18\x04 \x01(\v2\x1f.arc.relay.v1.RegisterNameFrameH\x00R\fregisterName\x12-\n" +
	"\x04ping\x18\x05 \x01(\v2\x17.arc.relay.v1.PingFrameH\x00R\x04ping\x129\n" +
	"\bdiscover\x18\x06 \x01(\v2\x1b.arc.relay.v1.DiscoverFrameH\x00R\bdiscover\x12F\n" +
	"\rupdate_labels\x18\a \x01(\v2\x1f.arc.relay.v1.UpdateLabelsFrameH\x00R\fupdateLabels\x12C\n" +
	"\fupdate_state\x18\b \x01(\v2\x1e.arc.relay.v1.UpdateStateFrameH\x00R\vupdateStateB\a\n" +
	"\x05frame\"a\n" +
	"\tSendFrame\x122\n" +
	"\benvelope\x18\x01 \x01(\v2\x16.arc.relay.v1.EnvelopeR\benvelope\x12 \n" +
	"\vcorrelation\x18\x02 \x01(\tR\vcorrelation\"\xc9\x02\n" +
	"\x0eSubscribeFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\x06labels\x18\x02 \x03(\v2(.arc.relay.v1.SubscribeFrame.LabelsEntryR\x06labels\x12P\n" +
	"\ftyped_labels\x18\x03 \x03(\v2-.arc.relay.v1.SubscribeFrame.TypedLabelsEntryR\vtypedLabels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aX\n" +
	"\x10TypedLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.arc.relay.v1.LabelValueR\x05value:\x028\x01\"\"\n" +
	"\x10UnsubscribeFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x11RegisterNameFrame\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"Q\n" +
	"\tPingFrame\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12.\n" +
	"\x13measured_latency_ns\x18\x02 \x01(\x03R\x11measuredLatencyNs\"\xea\x02\n" +
	"\x11UpdateLabelsFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12C\n" +
	"\x06labels\x18\x02 \x03(\v2+.arc.relay.v1.UpdateLabelsFrame.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06remove\x18\x03 \x03(\tR\x06remove\x12S\n" +
	"\ftyped_labels\x18\x04 \x03(\v20.arc.relay.v1.UpdateLabelsFrame.TypedLabelsEntryR\vtypedLabels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aX\n" +
	"\x10TypedLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.arc.relay.v1.LabelValueR\x05value:\x028\x01\"\xcf\x01\n" +
	"\x10UpdateStateFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12?\n" +
	"\x05state\x18\x02 \x03(\v2).arc.relay.v1.UpdateStateFrame.StateEntryR\x05state\x12\x16\n" +
	"\x06remove\x18\x03 \x03(\tR\x06remove\x1aR\n" +
	"\n" +
	"StateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.arc.relay.v1.LabelValueR\x05value:\x028\x01\"\xb5\x02\n" +
	"\vServerFrame\x126\n" +
	"\adeliver\x18\x01 \x01(\v2\x1a.arc.relay.v1.DeliverFrameH\x00R\adeliver\x126\n" +
	"\areceipt\x18\x02 \x01(\v2\x1a.arc.relay.v1.ReceiptFrameH\x00R\areceipt\x120\n" +
	"\x05error\x18\x03 \x01(\v2\x18.arc.relay.v1.ErrorFrameH\x00R\x05error\x12-\n" +
	"\x04pong\x18\x04 \x01(\v2\x17.arc.relay.v1.PongFrameH\x00R\x04pong\x12L\n" +
	"\x0fdiscover_result\x18\x05 \x01(\v2!.arc.relay.v1.DiscoverResultFrameH\x00R\x0ediscoverResultB\a\n" +
	"\x05frame\"k\n" +
	"\fDeliverFrame\x122\n" +
	"\benvelope\x18\x01 \x01(\v2\x16.arc.relay.v1.EnvelopeR\benvelope\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\"?\n" +
	"\fReceiptFrame\x12/\n" +
	"\areceipt\x18\x01 \x01(\v2\x15.arc.relay.v1.ReceiptR\areceipt\"\x92\x01\n" +
	"\n" +
	"ErrorFrame\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12 \n" +
	"\vcorrelation\x18\x05 \x01(\tR\vcorrelation\"B\n" +
	"\tPongFrame\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\"\xe3\x01\n" +
	"\rDiscoverFrame\x12?\n" +
	"\x06filter\x18\x01 \x03(\v2'.arc.relay.v1.DiscoverFrame.FilterEntryR\x06filter\x12 \n" +
	"\vcorrelation\x18\x02 \x01(\tR\vcorrelation\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1e\n" +
	"\n" +
	"expression\x18\x04 \x01(\tR\n" +
	"expression\x1a9\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x01\n" +
	"\x13DiscoverResultFrame\x12 \n" +
	"\vcorrelation\x18\x01 \x01(\tR\vcorrelation\x128\n" +
	"\tproviders\x18\x02 \x03(\v2\x1a.arc.relay.v1.ProviderInfoR\tproviders\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\xef\x05\n" +
	"\fProviderInfo\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12>\n" +
	"\x06labels\x18\x03 \x03(\v2&.arc.relay.v1.ProviderInfo.LabelsEntryR\x06labels\x12'\n" +
	"\x0fsubscription_id\x18\x04 \x01(\tR\x0esubscriptionId\x12!\n" +
	"\frelay_pubkey\x18\x05 \x01(\fR\vrelayPubkey\x12\x18\n" +
	"\apetname\x18\x06 \x01(\tR\apetname\x12\x1d\n" +
	"\n" +
	"latency_ns\x18\a \x01(\x03R\tlatencyNs\x12 \n" +
	"\flast_seen_ns\x18\b \x01(\x03R\n" +
	"lastSeenNs\x12!\n" +
	"\fconnected_ns\x18\t \x01(\x03R\vconnectedNs\x123\n" +
	"\x16inter_relay_latency_ns\x18\n" +
	" \x01(\x03R\x13interRelayLatencyNs\x12N\n" +
	"\ftyped_labels\x18\v \x03(\v2+.arc.relay.v1.ProviderInfo.TypedLabelsEntryR\vtypedLabels\x12;\n" +
	"\x05state\x18\f \x03(\v2%.arc.relay.v1.ProviderInfo.StateEntryR\x05state\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aX\n" +
	"\x10TypedLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.arc.relay.v1.LabelValueR\x05value:\x028\x01\x1aR\n" +
	"\n" +
	"StateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.arc.relay.v1.LabelValueR\x05value:\x028\x01\"o\n" +
	"\x16ForwardEnvelopeRequest\x122\n" +
	"\benvelope\x18\x01 \x01(\v2\x16.arc.relay.v1.EnvelopeR\benvelope\x12!\n" +
	"\fsource_relay\x18\x02 \x01(\tR\vsourceRelay\"O\n" +
	"\x17ForwardEnvelopeResponse\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\x05R\tdelivered\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\")\n" +
	"\x11GossipJoinRequest\x12\x14\n" +
	"\x05peers\x18\x01 \x03(\tR\x05peers\",\n" +
	"\x12GossipJoinResponse\x12\x16\n" +
	"\x06joined\x18\x01 \x01(\x05R\x06joined\"\x16\n" +
	"\x14GossipMembersRequest\"M\n" +
	"\x15GossipMembersResponse\x124\n" +
	"\amembers\x18\x01 \x03(\v2\x1a.arc.relay.v1.GossipMemberR\amembers\"\xfc\x01\n" +
	"\fGossipMember\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1b\n" +
	"\tgrpc_addr\x18\x03 \x01(\tR\bgrpcAddr\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06pubkey\x18\x05 \x01(\fR\x06pubkey\x12 \n" +
	"\vconnections\x18\x06 \x01(\x05R\vconnections\x12\x1b\n" +
	"\tuptime_ns\x18\a \x01(\x03R\buptimeNs\x12\x1d\n" +
	"\n" +
	"latency_ns\x18\b \x01(\x03R\tlatencyNs\x12\x19\n" +
	"\bis_local\x18\t \x01(\bR\aisLocal\"\x14\n" +
	"\x12GossipLeaveRequest\"\x15\n" +
	"\x13GossipLeaveResponse*`\n" +
	"\rReceiptStatus\x12\x1e\n" +
	"\x1aRECEIPT_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RECEIPT_STATUS_ACK\x10\x01\x12\x17\n" +
	"\x13RECEIPT_STATUS_NACK\x10\x022\xb2\x03\n" +
	"\fRelayService\x12C\n" +
	"\aConnect\x12\x19.arc.relay.v1.ClientFrame\x1a\x19.arc.relay.v1.ServerFrame(\x010\x01\x12^\n" +
	"\x0fForwardEnvelope\x12$.arc.relay.v1.ForwardEnvelopeRequest\x1a%.arc.relay.v1.ForwardEnvelopeResponse\x12O\n" +
	"\n" +
	"GossipJoin\x12\x1f.arc.relay.v1.GossipJoinRequest\x1a .arc.relay.v1.GossipJoinResponse\x12X\n" +
	"\rGossipMembers\x12\".arc.relay.v1.GossipMembersRequest\x1a#.arc.relay.v1.GossipMembersResponse\x12R\n" +
	"\vGossipLeave\x12 .arc.relay.v1.GossipLeaveRequest\x1a!.arc.relay.v1.GossipLeaveResponseB5Z3github.com/gezibash/arc/v2/api/arc/relay/v1;relayv1b\x06proto3"

var (
	file_arc_relay_v1_relay_proto_rawDescOnce sync.Once
	file_arc_relay_v1_relay_proto_rawDescData []byte
)

func file_arc_relay_v1_relay_proto_rawDescGZIP() []byte {
	file_arc_relay_v1_relay_proto_rawDescOnce.Do(func() {
		file_arc_relay_v1_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arc_relay_v1_relay_proto_rawDesc), len(file_arc_relay_v1_relay_proto_rawDesc)))
	})
	return file_arc_relay_v1_relay_proto_rawDescData
}

var file_arc_relay_v1_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_arc_relay_v1_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_arc_relay_v1_relay_proto_goTypes = []any{
	(ReceiptStatus)(0),              // 0: arc.relay.v1.ReceiptStatus
	(*Envelope)(nil),                // 1: arc.relay.v1.Envelope
	(*Receipt)(nil),                 // 2: arc.relay.v1.Receipt
	(*LabelValue)(nil),              // 3: arc.relay.v1.LabelValue
	(*ClientFrame)(nil),             // 4: arc.relay.v1.ClientFrame
	(*SendFrame)(nil),               // 5: arc.relay.v1.SendFrame
	(*SubscribeFrame)(nil),          // 6: arc.relay.v1.SubscribeFrame
	(*UnsubscribeFrame)(nil),        // 7: arc.relay.v1.UnsubscribeFrame
	(*RegisterNameFrame)(nil),       // 8: arc.relay.v1.RegisterNameFrame
	(*PingFrame)(nil),               // 9: arc.relay.v1.PingFrame
	(*UpdateLabelsFrame)(nil),       // 10: arc.relay.v1.UpdateLabelsFrame
	(*UpdateStateFrame)(nil),        // 11: arc.relay.v1.UpdateStateFrame
	(*ServerFrame)(nil),             // 12: arc.relay.v1.ServerFrame
	(*DeliverFrame)(nil),            // 13: arc.relay.v1.DeliverFrame
	(*ReceiptFrame)(nil),            // 14: arc.relay.v1.ReceiptFrame
	(*ErrorFrame)(nil),              // 15: arc.relay.v1.ErrorFrame
	(*PongFrame)(nil),               // 16: arc.relay.v1.PongFrame
	(*DiscoverFrame)(nil),           // 17: arc.relay.v1.DiscoverFrame
	(*DiscoverResultFrame)(nil),     // 18: arc.relay.v1.DiscoverResultFrame
	(*ProviderInfo)(nil),            // 19: arc.relay.v1.ProviderInfo
	(*ForwardEnvelopeRequest)(nil),  // 20: arc.relay.v1.ForwardEnvelopeRequest
	(*ForwardEnvelopeResponse)(nil), // 21: arc.relay.v1.ForwardEnvelopeResponse
	(*GossipJoinRequest)(nil),       // 22: arc.relay.v1.GossipJoinRequest
	(*GossipJoinResponse)(nil),      // 23: arc.relay.v1.GossipJoinResponse
	(*GossipMembersRequest)(nil),    // 24: arc.relay.v1.GossipMembersRequest
	(*GossipMembersResponse)(nil),   // 25: arc.relay.v1.GossipMembersResponse
	(*GossipMember)(nil),            // 26: arc.relay.v1.GossipMember
	(*GossipLeaveRequest)(nil),      // 27: arc.relay.v1.GossipLeaveRequest
	(*GossipLeaveResponse)(nil),     // 28: arc.relay.v1.GossipLeaveResponse
	nil,                             // 29: arc.relay.v1.Envelope.LabelsEntry
	nil,                             // 30: arc.relay.v1.SubscribeFrame.LabelsEntry
	nil,                             // 31: arc.relay.v1.SubscribeFrame.TypedLabelsEntry
	nil,                             // 32: arc.relay.v1.UpdateLabelsFrame.LabelsEntry
	nil,                             // 33: arc.relay.v1.UpdateLabelsFrame.TypedLabelsEntry
	nil,                             // 34: arc.relay.v1.UpdateStateFrame.StateEntry
	nil,                             // 35: arc.relay.v1.DiscoverFrame.FilterEntry
	nil,                             // 36: arc.relay.v1.ProviderInfo.LabelsEntry
	nil,                             // 37: arc.relay.v1.ProviderInfo.TypedLabelsEntry
	nil,                             // 38: arc.relay.v1.ProviderInfo.StateEntry
}
var file_arc_relay_v1_relay_proto_depIdxs = []int32{
	29, // 0: arc.relay.v1.Envelope.labels:type_name -> arc.relay.v1.Envelope.LabelsEntry
	0,  // 1: arc.relay.v1.Receipt.status:type_name -> arc.relay.v1.ReceiptStatus
	5,  // 2: arc.relay.v1.ClientFrame.send:type_name -> arc.relay.v1.SendFrame
	6,  // 3: arc.relay.v1.ClientFrame.subscribe:type_name -> arc.relay.v1.SubscribeFrame
	7,  // 4: arc.relay.v1.ClientFrame.unsubscribe:type_name -> arc.relay.v1.UnsubscribeFrame
	8,  // 5: arc.relay.v1.ClientFrame.register_name:type_name -> arc.relay.v1.RegisterNameFrame
	9,  // 6: arc.relay.v1.ClientFrame.ping:type_name -> arc.relay.v1.PingFrame
	17, // 7: arc.relay.v1.ClientFrame.discover:type_name -> arc.relay.v1.DiscoverFrame
	10, // 8: arc.relay.v1.ClientFrame.update_labels:type_name -> arc.relay.v1.UpdateLabelsFrame
	11, // 9: arc.relay.v1.ClientFrame.update_state:type_name -> arc.relay.v1.UpdateStateFrame
	1,  // 10: arc.relay.v1.SendFrame.envelope:type_name -> arc.relay.v1.Envelope
	30, // 11: arc.relay.v1.SubscribeFrame.labels:type_name -> arc.relay.v1.SubscribeFrame.LabelsEntry
	31, // 12: arc.relay.v1.SubscribeFrame.typed_labels:type_name -> arc.relay.v1.SubscribeFrame.TypedLabelsEntry
	32, // 13: arc.relay.v1.UpdateLabelsFrame.labels:type_name -> arc.relay.v1.UpdateLabelsFrame.LabelsEntry
	33, // 14: arc.relay.v1.UpdateLabelsFrame.typed_labels:type_name -> arc.relay.v1.UpdateLabelsFrame.TypedLabelsEntry
	34, // 15: arc.relay.v1.UpdateStateFrame.state:type_name -> arc.relay.v1.UpdateStateFrame.StateEntry
	13, // 16: arc.relay.v1.ServerFrame.deliver:type_name -> arc.relay.v1.DeliverFrame
	14, // 17: arc.relay.v1.ServerFrame.receipt:type_name -> arc.relay.v1.ReceiptFrame
	15, // 18: arc.relay.v1.ServerFrame.error:type_name -> arc.relay.v1.ErrorFrame
	16, // 19: arc.relay.v1.ServerFrame.pong:type_name -> arc.relay.v1.PongFrame
	18, // 20: arc.relay.v1.ServerFrame.discover_result:type_name -> arc.relay.v1.DiscoverResultFrame
	1,  // 21: arc.relay.v1.DeliverFrame.envelope:type_name -> arc.relay.v1.Envelope
	2,  // 22: arc.relay.v1.ReceiptFrame.receipt:type_name -> arc.relay.v1.Receipt
	35, // 23: arc.relay.v1.DiscoverFrame.filter:type_name -> arc.relay.v1.DiscoverFrame.FilterEntry
	19, // 24: arc.relay.v1.DiscoverResultFrame.providers:type_name -> arc.relay.v1.ProviderInfo
	36, // 25: arc.relay.v1.ProviderInfo.labels:type_name -> arc.relay.v1.ProviderInfo.LabelsEntry
	37, // 26: arc.relay.v1.ProviderInfo.typed_labels:type_name -> arc.relay.v1.ProviderInfo.TypedLabelsEntry
	38, // 27: arc.relay.v1.ProviderInfo.state:type_name -> arc.relay.v1.ProviderInfo.StateEntry
	1,  // 28: arc.relay.v1.ForwardEnvelopeRequest.envelope:type_name -> arc.relay.v1.Envelope
	26, // 29: arc.relay.v1.GossipMembersResponse.members:type_name -> arc.relay.v1.GossipMember
	3,  // 30: arc.relay.v1.SubscribeFrame.TypedLabelsEntry.value:type_name -> arc.relay.v1.LabelValue
	3,  // 31: arc.relay.v1.UpdateLabelsFrame.TypedLabelsEntry.value:type_name -> arc.relay.v1.LabelValue
	3,  // 32: arc.relay.v1.UpdateStateFrame.StateEntry.value:type_name -> arc.relay.v1.LabelValue
	3,  // 33: arc.relay.v1.ProviderInfo.TypedLabelsEntry.value:type_name -> arc.relay.v1.LabelValue
	3,  // 34: arc.relay.v1.ProviderInfo.StateEntry.value:type_name -> arc.relay.v1.LabelValue
	4,  // 35: arc.relay.v1.RelayService.Connect:input_type -> arc.relay.v1.ClientFrame
	20, // 36: arc.relay.v1.RelayService.ForwardEnvelope:input_type -> arc.relay.v1.ForwardEnvelopeRequest
	22, // 37: arc.relay.v1.RelayService.GossipJoin:input_type -> arc.relay.v1.GossipJoinRequest
	24, // 38: arc.relay.v1.RelayService.GossipMembers:input_type -> arc.relay.v1.GossipMembersRequest
	27, // 39: arc.relay.v1.RelayService.GossipLeave:input_type -> arc.relay.v1.GossipLeaveRequest
	12, // 40: arc.relay.v1.RelayService.Connect:output_type -> arc.relay.v1.ServerFrame
	21, // 41: arc.relay.v1.RelayService.ForwardEnvelope:output_type -> arc.relay.v1.ForwardEnvelopeResponse
	23, // 42: arc.relay.v1.RelayService.GossipJoin:output_type -> arc.relay.v1.GossipJoinResponse
	25, // 43: arc.relay.v1.RelayService.GossipMembers:output_type -> arc.relay.v1.GossipMembersResponse
	28, // 44: arc.relay.v1.RelayService.GossipLeave:output_type -> arc.relay.v1.GossipLeaveResponse
	40, // [40:45] is the sub-list for method output_type
	35, // [35:40] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_arc_relay_v1_relay_proto_init() }
func file_arc_relay_v1_relay_proto_init() {
	if File_arc_relay_v1_relay_proto != nil {
		return
	}
	file_arc_relay_v1_relay_proto_msgTypes[2].OneofWrappers = []any{
		(*LabelValue_StringValue)(nil),
		(*LabelValue_IntValue)(nil),
		(*LabelValue_DoubleValue)(nil),
		(*LabelValue_BoolValue)(nil),
	}
	file_arc_relay_v1_relay_proto_msgTypes[3].OneofWrappers = []any{
		(*ClientFrame_Send)(nil),
		(*ClientFrame_Subscribe)(nil),
		(*ClientFrame_Unsubscribe)(nil),
		(*ClientFrame_RegisterName)(nil),
		(*ClientFrame_Ping)(nil),
		(*ClientFrame_Discover)(nil),
		(*ClientFrame_UpdateLabels)(nil),
		(*ClientFrame_UpdateState)(nil),
	}
	file_arc_relay_v1_relay_proto_msgTypes[11].OneofWrappers = []any{
		(*ServerFrame_Deliver)(nil),
		(*ServerFrame_Receipt)(nil),
		(*ServerFrame_Error)(nil),
		(*ServerFrame_Pong)(nil),
		(*ServerFrame_DiscoverResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arc_relay_v1_relay_proto_rawDesc), len(file_arc_relay_v1_relay_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arc_relay_v1_relay_proto_goTypes,
		DependencyIndexes: file_arc_relay_v1_relay_proto_depIdxs,
		EnumInfos:         file_arc_relay_v1_relay_proto_enumTypes,
		MessageInfos:      file_arc_relay_v1_relay_proto_msgTypes,
	}.Build()
	File_arc_relay_v1_relay_proto = out.File
	file_arc_relay_v1_relay_proto_goTypes = nil
	file_arc_relay_v1_relay_proto_depIdxs = nil
}
