// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: arc/relay/v1/relay.proto

package relayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReceiptStatus int32

const (
	ReceiptStatus_RECEIPT_STATUS_UNSPECIFIED ReceiptStatus = 0
	ReceiptStatus_RECEIPT_STATUS_ACK         ReceiptStatus = 1 // Envelope accepted and routed
	ReceiptStatus_RECEIPT_STATUS_NACK        ReceiptStatus = 2 // Envelope rejected (see reason)
)

// Enum value maps for ReceiptStatus.
var (
	ReceiptStatus_name = map[int32]string{
		0: "RECEIPT_STATUS_UNSPECIFIED",
		1: "RECEIPT_STATUS_ACK",
		2: "RECEIPT_STATUS_NACK",
	}
	ReceiptStatus_value = map[string]int32{
		"RECEIPT_STATUS_UNSPECIFIED": 0,
		"RECEIPT_STATUS_ACK":         1,
		"RECEIPT_STATUS_NACK":        2,
	}
)

func (x ReceiptStatus) Enum() *ReceiptStatus {
	p := new(ReceiptStatus)
	*p = x
	return p
}

func (x ReceiptStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReceiptStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_arc_relay_v1_relay_proto_enumTypes[0].Descriptor()
}

func (ReceiptStatus) Type() protoreflect.EnumType {
	return &file_arc_relay_v1_relay_proto_enumTypes[0]
}

func (x ReceiptStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReceiptStatus.Descriptor instead.
func (ReceiptStatus) EnumDescriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{0}
}

// Envelope is the unit of transmission through the relay.
// Content-addressed by SHA-256 hash of (labels + payload).
//
// Routing labels live here. The payload (typically an arc.Message) may have
// its own labels for indexing — relay doesn't inspect those.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content-addressed reference (SHA-256 hash). Computed by relay if empty.
	Ref []byte `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Routing labels (exact-match). Special key:
	//
	//	"to" - addressed routing to @name (requires RegisterNameFrame)
	//
	// All other keys use standard label matching. Capabilities are just labels:
	//
	//	{"capability": "storage"} - routes to subscribers with that label
	Labels map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Opaque payload, typically a serialized arc.Message. Relay does not inspect this.
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Ed25519 signature over (labels + payload) by sender.
	Signature []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	// Sender's public key (32 bytes Ed25519).
	Sender        []byte `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetRef() []byte {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Envelope) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Envelope) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

// Receipt acknowledges envelope processing by the relay.
// "Delivered" means queued in subscriber buffers, NOT processed by app.
type Receipt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference of the envelope this receipt is for.
	Ref []byte `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Client-provided correlation ID, echoed back.
	Correlation string `protobuf:"bytes,2,opt,name=correlation,proto3" json:"correlation,omitempty"`
	// Receipt status.
	Status ReceiptStatus `protobuf:"varint,3,opt,name=status,proto3,enum=arc.relay.v1.ReceiptStatus" json:"status,omitempty"`
	// Number of subscriber buffers that accepted the envelope.
	Delivered int32 `protobuf:"varint,4,opt,name=delivered,proto3" json:"delivered,omitempty"`
	// Human-readable reason (for NACK).
	Reason        string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{1}
}

func (x *Receipt) GetRef() []byte {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Receipt) GetCorrelation() string {
	if x != nil {
		return x.Correlation
	}
	return ""
}

func (x *Receipt) GetStatus() ReceiptStatus {
	if x != nil {
		return x.Status
	}
	return ReceiptStatus_RECEIPT_STATUS_UNSPECIFIED
}

func (x *Receipt) GetDelivered() int32 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

func (x *Receipt) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ClientFrame_Send
	//	*ClientFrame_Subscribe
	//	*ClientFrame_Unsubscribe
	//	*ClientFrame_RegisterName
	//	*ClientFrame_Ping
	Frame         isClientFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{2}
}

func (x *ClientFrame) GetFrame() isClientFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ClientFrame) GetSend() *SendFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Send); ok {
			return x.Send
		}
	}
	return nil
}

func (x *ClientFrame) GetSubscribe() *SubscribeFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *ClientFrame) GetUnsubscribe() *UnsubscribeFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *ClientFrame) GetRegisterName() *RegisterNameFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_RegisterName); ok {
			return x.RegisterName
		}
	}
	return nil
}

func (x *ClientFrame) GetPing() *PingFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isClientFrame_Frame interface {
	isClientFrame_Frame()
}

type ClientFrame_Send struct {
	Send *SendFrame `protobuf:"bytes,1,opt,name=send,proto3,oneof"`
}

type ClientFrame_Subscribe struct {
	Subscribe *SubscribeFrame `protobuf:"bytes,2,opt,name=subscribe,proto3,oneof"`
}

type ClientFrame_Unsubscribe struct {
	Unsubscribe *UnsubscribeFrame `protobuf:"bytes,3,opt,name=unsubscribe,proto3,oneof"`
}

type ClientFrame_RegisterName struct {
	RegisterName *RegisterNameFrame `protobuf:"bytes,4,opt,name=register_name,json=registerName,proto3,oneof"`
}

type ClientFrame_Ping struct {
	Ping *PingFrame `protobuf:"bytes,5,opt,name=ping,proto3,oneof"`
}

func (*ClientFrame_Send) isClientFrame_Frame() {}

func (*ClientFrame_Subscribe) isClientFrame_Frame() {}

func (*ClientFrame_Unsubscribe) isClientFrame_Frame() {}

func (*ClientFrame_RegisterName) isClientFrame_Frame() {}

func (*ClientFrame_Ping) isClientFrame_Frame() {}

// SendFrame publishes an envelope through the relay.
type SendFrame struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Envelope *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// Optional correlation ID for matching receipts.
	Correlation   string `protobuf:"bytes,2,opt,name=correlation,proto3" json:"correlation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFrame) Reset() {
	*x = SendFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFrame) ProtoMessage() {}

func (x *SendFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFrame.ProtoReflect.Descriptor instead.
func (*SendFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{3}
}

func (x *SendFrame) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *SendFrame) GetCorrelation() string {
	if x != nil {
		return x.Correlation
	}
	return ""
}

// SubscribeFrame registers interest in envelopes matching labels.
// Uses exact-match semantics (no CEL, no wildcards).
type SubscribeFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subscription ID (client-generated, for unsubscribe).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Labels to match. All specified labels must match exactly.
	// Empty map means "match all" (not recommended).
	Labels        map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeFrame) Reset() {
	*x = SubscribeFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeFrame) ProtoMessage() {}

func (x *SubscribeFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeFrame.ProtoReflect.Descriptor instead.
func (*SubscribeFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeFrame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubscribeFrame) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// UnsubscribeFrame removes a subscription.
type UnsubscribeFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subscription ID from SubscribeFrame.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeFrame) Reset() {
	*x = UnsubscribeFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeFrame) ProtoMessage() {}

func (x *UnsubscribeFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeFrame.ProtoReflect.Descriptor instead.
func (*UnsubscribeFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{5}
}

func (x *UnsubscribeFrame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// RegisterNameFrame claims an addressed name for this connection.
// Names are prefixed with @ (e.g., "@alice").
type RegisterNameFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name to register (without @ prefix).
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNameFrame) Reset() {
	*x = RegisterNameFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNameFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNameFrame) ProtoMessage() {}

func (x *RegisterNameFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNameFrame.ProtoReflect.Descriptor instead.
func (*RegisterNameFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterNameFrame) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// PingFrame is a keepalive.
type PingFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingFrame) Reset() {
	*x = PingFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingFrame) ProtoMessage() {}

func (x *PingFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingFrame.ProtoReflect.Descriptor instead.
func (*PingFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{7}
}

func (x *PingFrame) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ServerFrame_Deliver
	//	*ServerFrame_Receipt
	//	*ServerFrame_Error
	//	*ServerFrame_Pong
	Frame         isServerFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{8}
}

func (x *ServerFrame) GetFrame() isServerFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ServerFrame) GetDeliver() *DeliverFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Deliver); ok {
			return x.Deliver
		}
	}
	return nil
}

func (x *ServerFrame) GetReceipt() *ReceiptFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Receipt); ok {
			return x.Receipt
		}
	}
	return nil
}

func (x *ServerFrame) GetError() *ErrorFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerFrame) GetPong() *PongFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isServerFrame_Frame interface {
	isServerFrame_Frame()
}

type ServerFrame_Deliver struct {
	Deliver *DeliverFrame `protobuf:"bytes,1,opt,name=deliver,proto3,oneof"`
}

type ServerFrame_Receipt struct {
	Receipt *ReceiptFrame `protobuf:"bytes,2,opt,name=receipt,proto3,oneof"`
}

type ServerFrame_Error struct {
	Error *ErrorFrame `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type ServerFrame_Pong struct {
	Pong *PongFrame `protobuf:"bytes,4,opt,name=pong,proto3,oneof"`
}

func (*ServerFrame_Deliver) isServerFrame_Frame() {}

func (*ServerFrame_Receipt) isServerFrame_Frame() {}

func (*ServerFrame_Error) isServerFrame_Frame() {}

func (*ServerFrame_Pong) isServerFrame_Frame() {}

// DeliverFrame delivers an envelope to a subscriber.
type DeliverFrame struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Envelope *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// Which subscription matched (from SubscribeFrame.id).
	SubscriptionId string `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeliverFrame) Reset() {
	*x = DeliverFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverFrame) ProtoMessage() {}

func (x *DeliverFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverFrame.ProtoReflect.Descriptor instead.
func (*DeliverFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{9}
}

func (x *DeliverFrame) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *DeliverFrame) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

// ReceiptFrame wraps a Receipt for the stream.
type ReceiptFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *Receipt               `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiptFrame) Reset() {
	*x = ReceiptFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptFrame) ProtoMessage() {}

func (x *ReceiptFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptFrame.ProtoReflect.Descriptor instead.
func (*ReceiptFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{10}
}

func (x *ReceiptFrame) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

// ErrorFrame reports an error (subscription failed, registration failed, etc.).
type ErrorFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gRPC-compatible error code.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Machine-readable error type (e.g., "NAME_TAKEN", "INVALID_SIGNATURE").
	Detail string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	// Whether client should retry.
	Retryable bool `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	// Which request this error is for (correlation or subscription ID).
	Correlation   string `protobuf:"bytes,5,opt,name=correlation,proto3" json:"correlation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorFrame) Reset() {
	*x = ErrorFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorFrame) ProtoMessage() {}

func (x *ErrorFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorFrame.ProtoReflect.Descriptor instead.
func (*ErrorFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{11}
}

func (x *ErrorFrame) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorFrame) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorFrame) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ErrorFrame) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ErrorFrame) GetCorrelation() string {
	if x != nil {
		return x.Correlation
	}
	return ""
}

// PongFrame responds to PingFrame.
type PongFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Nonce []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Server timestamp (unix nanos).
	ServerTime    int64 `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongFrame) Reset() {
	*x = PongFrame{}
	mi := &file_arc_relay_v1_relay_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongFrame) ProtoMessage() {}

func (x *PongFrame) ProtoReflect() protoreflect.Message {
	mi := &file_arc_relay_v1_relay_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongFrame.ProtoReflect.Descriptor instead.
func (*PongFrame) Descriptor() ([]byte, []int) {
	return file_arc_relay_v1_relay_proto_rawDescGZIP(), []int{12}
}

func (x *PongFrame) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *PongFrame) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

var File_arc_relay_v1_relay_proto protoreflect.FileDescriptor

const file_arc_relay_v1_relay_proto_rawDesc = "" +
	"\n" +
	"\x18arc/relay/v1/relay.proto\x12\farc.relay.v1\"\xe3\x01\n" +
	"\bEnvelope\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\fR\x03ref\x12:\n" +
	"\x06labels\x18\x02 \x03(\v2\".arc.relay.v1.Envelope.LabelsEntryR\x06labels\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12\x16\n" +
	"\x06sender\x18\x05 \x01(\fR\x06sender\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x01\n" +
	"\aReceipt\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\fR\x03ref\x12 \n" +
	"\vcorrelation\x18\x02 \x01(\tR\vcorrelation\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.arc.relay.v1.ReceiptStatusR\x06status\x12\x1c\n" +
	"\tdelivered\x18\x04 \x01(\x05R\tdelivered\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\xbe\x02\n" +
	"\vClientFrame\x12-\n" +
	"\x04send\x18\x01 \x01(\v2\x17.arc.relay.v1.SendFrameH\x00R\x04send\x12<\n" +
	"\tsubscribe\x18\x02 \x01(\v2\x1c.arc.relay.v1.SubscribeFrameH\x00R\tsubscribe\x12B\n" +
	"\vunsubscribe\x18\x03 \x01(\v2\x1e.arc.relay.v1.UnsubscribeFrameH\x00R\vunsubscribe\x12F\n" +
	"\rregister_name\x18\x04 \x01(\v2\x1f.arc.relay.v1.RegisterNameFrameH\x00R\fregisterName\x12-\n" +
	"\x04ping\x18\x05 \x01(\v2\x17.arc.relay.v1.PingFrameH\x00R\x04pingB\a\n" +
	"\x05frame\"a\n" +
	"\tSendFrame\x122\n" +
	"\benvelope\x18\x01 \x01(\v2\x16.arc.relay.v1.EnvelopeR\benvelope\x12 \n" +
	"\vcorrelation\x18\x02 \x01(\tR\vcorrelation\"\x9d\x01\n" +
	"\x0eSubscribeFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\x06labels\x18\x02 \x03(\v2(.arc.relay.v1.SubscribeFrame.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\"\n" +
	"\x10UnsubscribeFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x11RegisterNameFrame\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"!\n" +
	"\tPingFrame\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\"\xe7\x01\n" +
	"\vServerFrame\x126\n" +
	"\adeliver\x18\x01 \x01(\v2\x1a.arc.relay.v1.DeliverFrameH\x00R\adeliver\x126\n" +
	"\areceipt\x18\x02 \x01(\v2\x1a.arc.relay.v1.ReceiptFrameH\x00R\areceipt\x120\n" +
	"\x05error\x18\x03 \x01(\v2\x18.arc.relay.v1.ErrorFrameH\x00R\x05error\x12-\n" +
	"\x04pong\x18\x04 \x01(\v2\x17.arc.relay.v1.PongFrameH\x00R\x04pongB\a\n" +
	"\x05frame\"k\n" +
	"\fDeliverFrame\x122\n" +
	"\benvelope\x18\x01 \x01(\v2\x16.arc.relay.v1.EnvelopeR\benvelope\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\"?\n" +
	"\fReceiptFrame\x12/\n" +
	"\areceipt\x18\x01 \x01(\v2\x15.arc.relay.v1.ReceiptR\areceipt\"\x92\x01\n" +
	"\n" +
	"ErrorFrame\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12 \n" +
	"\vcorrelation\x18\x05 \x01(\tR\vcorrelation\"B\n" +
	"\tPongFrame\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime*`\n" +
	"\rReceiptStatus\x12\x1e\n" +
	"\x1aRECEIPT_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RECEIPT_STATUS_ACK\x10\x01\x12\x17\n" +
	"\x13RECEIPT_STATUS_NACK\x10\x022S\n" +
	"\fRelayService\x12C\n" +
	"\aConnect\x12\x19.arc.relay.v1.ClientFrame\x1a\x19.arc.relay.v1.ServerFrame(\x010\x01B7Z5github.com/gezibash/arc-node/api/arc/relay/v1;relayv1b\x06proto3"

var (
	file_arc_relay_v1_relay_proto_rawDescOnce sync.Once
	file_arc_relay_v1_relay_proto_rawDescData []byte
)

func file_arc_relay_v1_relay_proto_rawDescGZIP() []byte {
	file_arc_relay_v1_relay_proto_rawDescOnce.Do(func() {
		file_arc_relay_v1_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arc_relay_v1_relay_proto_rawDesc), len(file_arc_relay_v1_relay_proto_rawDesc)))
	})
	return file_arc_relay_v1_relay_proto_rawDescData
}

var file_arc_relay_v1_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_arc_relay_v1_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_arc_relay_v1_relay_proto_goTypes = []any{
	(ReceiptStatus)(0),        // 0: arc.relay.v1.ReceiptStatus
	(*Envelope)(nil),          // 1: arc.relay.v1.Envelope
	(*Receipt)(nil),           // 2: arc.relay.v1.Receipt
	(*ClientFrame)(nil),       // 3: arc.relay.v1.ClientFrame
	(*SendFrame)(nil),         // 4: arc.relay.v1.SendFrame
	(*SubscribeFrame)(nil),    // 5: arc.relay.v1.SubscribeFrame
	(*UnsubscribeFrame)(nil),  // 6: arc.relay.v1.UnsubscribeFrame
	(*RegisterNameFrame)(nil), // 7: arc.relay.v1.RegisterNameFrame
	(*PingFrame)(nil),         // 8: arc.relay.v1.PingFrame
	(*ServerFrame)(nil),       // 9: arc.relay.v1.ServerFrame
	(*DeliverFrame)(nil),      // 10: arc.relay.v1.DeliverFrame
	(*ReceiptFrame)(nil),      // 11: arc.relay.v1.ReceiptFrame
	(*ErrorFrame)(nil),        // 12: arc.relay.v1.ErrorFrame
	(*PongFrame)(nil),         // 13: arc.relay.v1.PongFrame
	nil,                       // 14: arc.relay.v1.Envelope.LabelsEntry
	nil,                       // 15: arc.relay.v1.SubscribeFrame.LabelsEntry
}
var file_arc_relay_v1_relay_proto_depIdxs = []int32{
	14, // 0: arc.relay.v1.Envelope.labels:type_name -> arc.relay.v1.Envelope.LabelsEntry
	0,  // 1: arc.relay.v1.Receipt.status:type_name -> arc.relay.v1.ReceiptStatus
	4,  // 2: arc.relay.v1.ClientFrame.send:type_name -> arc.relay.v1.SendFrame
	5,  // 3: arc.relay.v1.ClientFrame.subscribe:type_name -> arc.relay.v1.SubscribeFrame
	6,  // 4: arc.relay.v1.ClientFrame.unsubscribe:type_name -> arc.relay.v1.UnsubscribeFrame
	7,  // 5: arc.relay.v1.ClientFrame.register_name:type_name -> arc.relay.v1.RegisterNameFrame
	8,  // 6: arc.relay.v1.ClientFrame.ping:type_name -> arc.relay.v1.PingFrame
	1,  // 7: arc.relay.v1.SendFrame.envelope:type_name -> arc.relay.v1.Envelope
	15, // 8: arc.relay.v1.SubscribeFrame.labels:type_name -> arc.relay.v1.SubscribeFrame.LabelsEntry
	10, // 9: arc.relay.v1.ServerFrame.deliver:type_name -> arc.relay.v1.DeliverFrame
	11, // 10: arc.relay.v1.ServerFrame.receipt:type_name -> arc.relay.v1.ReceiptFrame
	12, // 11: arc.relay.v1.ServerFrame.error:type_name -> arc.relay.v1.ErrorFrame
	13, // 12: arc.relay.v1.ServerFrame.pong:type_name -> arc.relay.v1.PongFrame
	1,  // 13: arc.relay.v1.DeliverFrame.envelope:type_name -> arc.relay.v1.Envelope
	2,  // 14: arc.relay.v1.ReceiptFrame.receipt:type_name -> arc.relay.v1.Receipt
	3,  // 15: arc.relay.v1.RelayService.Connect:input_type -> arc.relay.v1.ClientFrame
	9,  // 16: arc.relay.v1.RelayService.Connect:output_type -> arc.relay.v1.ServerFrame
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_arc_relay_v1_relay_proto_init() }
func file_arc_relay_v1_relay_proto_init() {
	if File_arc_relay_v1_relay_proto != nil {
		return
	}
	file_arc_relay_v1_relay_proto_msgTypes[2].OneofWrappers = []any{
		(*ClientFrame_Send)(nil),
		(*ClientFrame_Subscribe)(nil),
		(*ClientFrame_Unsubscribe)(nil),
		(*ClientFrame_RegisterName)(nil),
		(*ClientFrame_Ping)(nil),
	}
	file_arc_relay_v1_relay_proto_msgTypes[8].OneofWrappers = []any{
		(*ServerFrame_Deliver)(nil),
		(*ServerFrame_Receipt)(nil),
		(*ServerFrame_Error)(nil),
		(*ServerFrame_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arc_relay_v1_relay_proto_rawDesc), len(file_arc_relay_v1_relay_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arc_relay_v1_relay_proto_goTypes,
		DependencyIndexes: file_arc_relay_v1_relay_proto_depIdxs,
		EnumInfos:         file_arc_relay_v1_relay_proto_enumTypes,
		MessageInfos:      file_arc_relay_v1_relay_proto_msgTypes,
	}.Build()
	File_arc_relay_v1_relay_proto = out.File
	file_arc_relay_v1_relay_proto_goTypes = nil
	file_arc_relay_v1_relay_proto_depIdxs = nil
}
