// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: arc/blob/v1/blob.proto

package blobv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConnectionMode indicates how to connect for blob transfer.
type ConnectionMode int32

const (
	ConnectionMode_CONNECTION_MODE_UNSPECIFIED ConnectionMode = 0
	// Store accepts direct connections.
	ConnectionMode_CONNECTION_MODE_DIRECT ConnectionMode = 1
	// Store only supports relay tunnel (firewalled).
	ConnectionMode_CONNECTION_MODE_RELAY_ONLY ConnectionMode = 2
)

// Enum value maps for ConnectionMode.
var (
	ConnectionMode_name = map[int32]string{
		0: "CONNECTION_MODE_UNSPECIFIED",
		1: "CONNECTION_MODE_DIRECT",
		2: "CONNECTION_MODE_RELAY_ONLY",
	}
	ConnectionMode_value = map[string]int32{
		"CONNECTION_MODE_UNSPECIFIED": 0,
		"CONNECTION_MODE_DIRECT":      1,
		"CONNECTION_MODE_RELAY_ONLY":  2,
	}
)

func (x ConnectionMode) Enum() *ConnectionMode {
	p := new(ConnectionMode)
	*p = x
	return p
}

func (x ConnectionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_arc_blob_v1_blob_proto_enumTypes[0].Descriptor()
}

func (ConnectionMode) Type() protoreflect.EnumType {
	return &file_arc_blob_v1_blob_proto_enumTypes[0]
}

func (x ConnectionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionMode.Descriptor instead.
func (ConnectionMode) EnumDescriptor() ([]byte, []int) {
	return file_arc_blob_v1_blob_proto_rawDescGZIP(), []int{0}
}

// Chunk is a piece of blob data for streaming.
type Chunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw blob data (recommended: 64KB - 1MB per chunk).
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Offset in the blob (for resumable transfers).
	Offset        int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_arc_blob_v1_blob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_arc_blob_v1_blob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_arc_blob_v1_blob_proto_rawDescGZIP(), []int{0}
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Chunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// PutResponse is returned after a successful Put.
type PutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content ID (SHA-256 hash of blob).
	Cid []byte `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	// Size in bytes.
	Size          int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_arc_blob_v1_blob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arc_blob_v1_blob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_arc_blob_v1_blob_proto_rawDescGZIP(), []int{1}
}

func (x *PutResponse) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *PutResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// GetRequest asks for a blob by CID.
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content ID to retrieve.
	Cid []byte `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	// Optional: start offset for range requests.
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Optional: max bytes to return (0 = all).
	Limit         int64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_arc_blob_v1_blob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arc_blob_v1_blob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_arc_blob_v1_blob_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *GetRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// BlobRequest is the envelope payload for blob requests via relay.
type BlobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*BlobRequest_Put
	//	*BlobRequest_Want
	//	*BlobRequest_Get
	Request       isBlobRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobRequest) Reset() {
	*x = BlobRequest{}
	mi := &file_arc_blob_v1_blob_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobRequest) ProtoMessage() {}

func (x *BlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arc_blob_v1_blob_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobRequest.ProtoReflect.Descriptor instead.
func (*BlobRequest) Descriptor() ([]byte, []int) {
	return file_arc_blob_v1_blob_proto_rawDescGZIP(), []int{3}
}

func (x *BlobRequest) GetRequest() isBlobRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *BlobRequest) GetPut() *PutIntent {
	if x != nil {
		if x, ok := x.Request.(*BlobRequest_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *BlobRequest) GetWant() *WantIntent {
	if x != nil {
		if x, ok := x.Request.(*BlobRequest_Want); ok {
			return x.Want
		}
	}
	return nil
}

func (x *BlobRequest) GetGet() *GetIntent {
	if x != nil {
		if x, ok := x.Request.(*BlobRequest_Get); ok {
			return x.Get
		}
	}
	return nil
}

type isBlobRequest_Request interface {
	isBlobRequest_Request()
}

type BlobRequest_Put struct {
	Put *PutIntent `protobuf:"bytes,1,opt,name=put,proto3,oneof"`
}

type BlobRequest_Want struct {
	Want *WantIntent `protobuf:"bytes,2,opt,name=want,proto3,oneof"`
}

type BlobRequest_Get struct {
	Get *GetIntent `protobuf:"bytes,3,opt,name=get,proto3,oneof"`
}

func (*BlobRequest_Put) isBlobRequest_Request() {}

func (*BlobRequest_Want) isBlobRequest_Request() {}

func (*BlobRequest_Get) isBlobRequest_Request() {}

// BlobResponse is the envelope payload for blob responses via relay.
type BlobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*BlobResponse_Stored
	//	*BlobResponse_Have
	//	*BlobResponse_Redirect
	//	*BlobResponse_Data
	//	*BlobResponse_Error
	Response      isBlobResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobResponse) Reset() {
	*x = BlobResponse{}
	mi := &file_arc_blob_v1_blob_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobResponse) ProtoMessage() {}

func (x *BlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arc_blob_v1_blob_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobResponse.ProtoReflect.Descriptor instead.
func (*BlobResponse) Descriptor() ([]byte, []int) {
	return file_arc_blob_v1_blob_proto_rawDescGZIP(), []int{4}
}

func (x *BlobResponse) GetResponse() isBlobResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *BlobResponse) GetStored() *StoredResponse {
	if x != nil {
		if x, ok := x.Response.(*BlobResponse_Stored); ok {
			return x.Stored
		}
	}
	return nil
}

func (x *BlobResponse) GetHave() *HaveResponse {
	if x != nil {
		if x, ok := x.Response.(*BlobResponse_Have); ok {
			return x.Have
		}
	}
	return nil
}

func (x *BlobResponse) GetRedirect() *RedirectResponse {
	if x != nil {
		if x, ok := x.Response.(*BlobResponse_Redirect); ok {
			return x.Redirect
		}
	}
	return nil
}

func (x *BlobResponse) GetData() *DataResponse {
	if x != nil {
		if x, ok := x.Response.(*BlobResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *BlobResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Response.(*BlobResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isBlobResponse_Response interface {
	isBlobResponse_Response()
}

type BlobResponse_Stored struct {
	Stored *StoredResponse `protobuf:"bytes,1,opt,name=stored,proto3,oneof"`
}

type BlobResponse_Have struct {
	Have *HaveResponse `protobuf:"bytes,2,opt,name=have,proto3,oneof"`
}

type BlobResponse_Redirect struct {
	Redirect *RedirectResponse `protobuf:"bytes,3,opt,name=redirect,proto3,oneof"`
}

type BlobResponse_Data struct {
	Data *DataResponse `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

type BlobResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*BlobResponse_Stored) isBlobResponse_Response() {}

func (*BlobResponse_Have) isBlobResponse_Response() {}

func (*BlobResponse_Redirect) isBlobResponse_Response() {}

func (*BlobResponse_Data) isBlobResponse_Response() {}

func (*BlobResponse_Error) isBlobResponse_Response() {}

// PutIntent signals intent to store a blob.
// For small blobs (< 1MB), include the data inline.
// For large blobs, leave data empty and expect REDIRECT response.
type PutIntent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Blob data (for small blobs, inline here).
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Size hint for large blobs (when data is empty).
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// Optional content type (e.g., "application/octet-stream").
	ContentType   string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutIntent) Reset() {
	*x = PutIntent{}
	mi := &file_arc_blob_v1_blob_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutIntent) ProtoMessage() {}

func (x *PutIntent) ProtoReflect() protoreflect.Message {
	mi := &file_arc_blob_v1_blob_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutIntent.ProtoReflect.Descriptor instead.
func (*PutIntent) Descriptor() ([]byte, []int) {
	return file_arc_blob_v1_blob_proto_rawDescGZIP(), []int{5}
}

func (x *PutIntent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PutIntent) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PutIntent) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// WantIntent asks which stores have a blob (discovery).
type WantIntent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content ID to find.
	Cid           []byte `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WantIntent) Reset() {
	*x = WantIntent{}
	mi := &file_arc_blob_v1_blob_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WantIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantIntent) ProtoMessage() {}

func (x *WantIntent) ProtoReflect() protoreflect.Message {
	mi := &file_arc_blob_v1_blob_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantIntent.ProtoReflect.Descriptor instead.
func (*WantIntent) Descriptor() ([]byte, []int) {
	return file_arc_blob_v1_blob_proto_rawDescGZIP(), []int{6}
}

func (x *WantIntent) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

// GetIntent requests blob retrieval.
type GetIntent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content ID to retrieve.
	Cid           []byte `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntent) Reset() {
	*x = GetIntent{}
	mi := &file_arc_blob_v1_blob_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntent) ProtoMessage() {}

func (x *GetIntent) ProtoReflect() protoreflect.Message {
	mi := &file_arc_blob_v1_blob_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntent.ProtoReflect.Descriptor instead.
func (*GetIntent) Descriptor() ([]byte, []int) {
	return file_arc_blob_v1_blob_proto_rawDescGZIP(), []int{7}
}

func (x *GetIntent) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

// StoredResponse confirms blob was stored.
type StoredResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content ID (SHA-256 hash).
	Cid []byte `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	// Size in bytes.
	Size          int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredResponse) Reset() {
	*x = StoredResponse{}
	mi := &file_arc_blob_v1_blob_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredResponse) ProtoMessage() {}

func (x *StoredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arc_blob_v1_blob_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredResponse.ProtoReflect.Descriptor instead.
func (*StoredResponse) Descriptor() ([]byte, []int) {
	return file_arc_blob_v1_blob_proto_rawDescGZIP(), []int{8}
}

func (x *StoredResponse) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *StoredResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// HaveResponse indicates this store has the requested blob.
// Sent in response to WantIntent.
type HaveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content ID.
	Cid []byte `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	// Size in bytes.
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// How to retrieve: direct connection or relay tunnel.
	Mode ConnectionMode `protobuf:"varint,3,opt,name=mode,proto3,enum=arc.blob.v1.ConnectionMode" json:"mode,omitempty"`
	// Direct connection address (if mode = DIRECT).
	// Format: "host:port"
	Address       string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HaveResponse) Reset() {
	*x = HaveResponse{}
	mi := &file_arc_blob_v1_blob_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HaveResponse) ProtoMessage() {}

func (x *HaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arc_blob_v1_blob_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HaveResponse.ProtoReflect.Descriptor instead.
func (*HaveResponse) Descriptor() ([]byte, []int) {
	return file_arc_blob_v1_blob_proto_rawDescGZIP(), []int{9}
}

func (x *HaveResponse) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *HaveResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *HaveResponse) GetMode() ConnectionMode {
	if x != nil {
		return x.Mode
	}
	return ConnectionMode_CONNECTION_MODE_UNSPECIFIED
}

func (x *HaveResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// RedirectResponse tells client to connect directly for transfer.
type RedirectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Direct connection address.
	// Format: "host:port"
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Content ID (for GET) or expected CID (for PUT after hash known).
	Cid           []byte `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectResponse) Reset() {
	*x = RedirectResponse{}
	mi := &file_arc_blob_v1_blob_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectResponse) ProtoMessage() {}

func (x *RedirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arc_blob_v1_blob_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectResponse.ProtoReflect.Descriptor instead.
func (*RedirectResponse) Descriptor() ([]byte, []int) {
	return file_arc_blob_v1_blob_proto_rawDescGZIP(), []int{10}
}

func (x *RedirectResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RedirectResponse) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

// DataResponse returns blob data inline (for small blobs).
type DataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content ID.
	Cid []byte `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	// Blob data.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Content type.
	ContentType   string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_arc_blob_v1_blob_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arc_blob_v1_blob_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_arc_blob_v1_blob_proto_rawDescGZIP(), []int{11}
}

func (x *DataResponse) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *DataResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// ErrorResponse reports an error.
type ErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error code (mirrors gRPC codes).
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable message.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_arc_blob_v1_blob_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arc_blob_v1_blob_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_arc_blob_v1_blob_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_arc_blob_v1_blob_proto protoreflect.FileDescriptor

const file_arc_blob_v1_blob_proto_rawDesc = "" +
	"\n" +
	"\x16arc/blob/v1/blob.proto\x12\varc.blob.v1\"3\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"3\n" +
	"\vPutResponse\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\fR\x03cid\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"L\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\fR\x03cid\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"\x9f\x01\n" +
	"\vBlobRequest\x12*\n" +
	"\x03put\x18\x01 \x01(\v2\x16.arc.blob.v1.PutIntentH\x00R\x03put\x12-\n" +
	"\x04want\x18\x02 \x01(\v2\x17.arc.blob.v1.WantIntentH\x00R\x04want\x12*\n" +
	"\x03get\x18\x03 \x01(\v2\x16.arc.blob.v1.GetIntentH\x00R\x03getB\t\n" +
	"\arequest\"\xa4\x02\n" +
	"\fBlobResponse\x125\n" +
	"\x06stored\x18\x01 \x01(\v2\x1b.arc.blob.v1.StoredResponseH\x00R\x06stored\x12/\n" +
	"\x04have\x18\x02 \x01(\v2\x19.arc.blob.v1.HaveResponseH\x00R\x04have\x12;\n" +
	"\bredirect\x18\x03 \x01(\v2\x1d.arc.blob.v1.RedirectResponseH\x00R\bredirect\x12/\n" +
	"\x04data\x18\x04 \x01(\v2\x19.arc.blob.v1.DataResponseH\x00R\x04data\x122\n" +
	"\x05error\x18\x05 \x01(\v2\x1a.arc.blob.v1.ErrorResponseH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"V\n" +
	"\tPutIntent\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"\x1e\n" +
	"\n" +
	"WantIntent\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\fR\x03cid\"\x1d\n" +
	"\tGetIntent\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\fR\x03cid\"6\n" +
	"\x0eStoredResponse\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\fR\x03cid\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"\x7f\n" +
	"\fHaveResponse\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\fR\x03cid\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12/\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x1b.arc.blob.v1.ConnectionModeR\x04mode\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\">\n" +
	"\x10RedirectResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\fR\x03cid\"W\n" +
	"\fDataResponse\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\fR\x03cid\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"=\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*m\n" +
	"\x0eConnectionMode\x12\x1f\n" +
	"\x1bCONNECTION_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CONNECTION_MODE_DIRECT\x10\x01\x12\x1e\n" +
	"\x1aCONNECTION_MODE_RELAY_ONLY\x10\x022z\n" +
	"\vBlobService\x125\n" +
	"\x03Put\x12\x12.arc.blob.v1.Chunk\x1a\x18.arc.blob.v1.PutResponse(\x01\x124\n" +
	"\x03Get\x12\x17.arc.blob.v1.GetRequest\x1a\x12.arc.blob.v1.Chunk0\x01B3Z1github.com/gezibash/arc/v2/api/arc/blob/v1;blobv1b\x06proto3"

var (
	file_arc_blob_v1_blob_proto_rawDescOnce sync.Once
	file_arc_blob_v1_blob_proto_rawDescData []byte
)

func file_arc_blob_v1_blob_proto_rawDescGZIP() []byte {
	file_arc_blob_v1_blob_proto_rawDescOnce.Do(func() {
		file_arc_blob_v1_blob_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arc_blob_v1_blob_proto_rawDesc), len(file_arc_blob_v1_blob_proto_rawDesc)))
	})
	return file_arc_blob_v1_blob_proto_rawDescData
}

var file_arc_blob_v1_blob_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_arc_blob_v1_blob_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_arc_blob_v1_blob_proto_goTypes = []any{
	(ConnectionMode)(0),      // 0: arc.blob.v1.ConnectionMode
	(*Chunk)(nil),            // 1: arc.blob.v1.Chunk
	(*PutResponse)(nil),      // 2: arc.blob.v1.PutResponse
	(*GetRequest)(nil),       // 3: arc.blob.v1.GetRequest
	(*BlobRequest)(nil),      // 4: arc.blob.v1.BlobRequest
	(*BlobResponse)(nil),     // 5: arc.blob.v1.BlobResponse
	(*PutIntent)(nil),        // 6: arc.blob.v1.PutIntent
	(*WantIntent)(nil),       // 7: arc.blob.v1.WantIntent
	(*GetIntent)(nil),        // 8: arc.blob.v1.GetIntent
	(*StoredResponse)(nil),   // 9: arc.blob.v1.StoredResponse
	(*HaveResponse)(nil),     // 10: arc.blob.v1.HaveResponse
	(*RedirectResponse)(nil), // 11: arc.blob.v1.RedirectResponse
	(*DataResponse)(nil),     // 12: arc.blob.v1.DataResponse
	(*ErrorResponse)(nil),    // 13: arc.blob.v1.ErrorResponse
}
var file_arc_blob_v1_blob_proto_depIdxs = []int32{
	6,  // 0: arc.blob.v1.BlobRequest.put:type_name -> arc.blob.v1.PutIntent
	7,  // 1: arc.blob.v1.BlobRequest.want:type_name -> arc.blob.v1.WantIntent
	8,  // 2: arc.blob.v1.BlobRequest.get:type_name -> arc.blob.v1.GetIntent
	9,  // 3: arc.blob.v1.BlobResponse.stored:type_name -> arc.blob.v1.StoredResponse
	10, // 4: arc.blob.v1.BlobResponse.have:type_name -> arc.blob.v1.HaveResponse
	11, // 5: arc.blob.v1.BlobResponse.redirect:type_name -> arc.blob.v1.RedirectResponse
	12, // 6: arc.blob.v1.BlobResponse.data:type_name -> arc.blob.v1.DataResponse
	13, // 7: arc.blob.v1.BlobResponse.error:type_name -> arc.blob.v1.ErrorResponse
	0,  // 8: arc.blob.v1.HaveResponse.mode:type_name -> arc.blob.v1.ConnectionMode
	1,  // 9: arc.blob.v1.BlobService.Put:input_type -> arc.blob.v1.Chunk
	3,  // 10: arc.blob.v1.BlobService.Get:input_type -> arc.blob.v1.GetRequest
	2,  // 11: arc.blob.v1.BlobService.Put:output_type -> arc.blob.v1.PutResponse
	1,  // 12: arc.blob.v1.BlobService.Get:output_type -> arc.blob.v1.Chunk
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_arc_blob_v1_blob_proto_init() }
func file_arc_blob_v1_blob_proto_init() {
	if File_arc_blob_v1_blob_proto != nil {
		return
	}
	file_arc_blob_v1_blob_proto_msgTypes[3].OneofWrappers = []any{
		(*BlobRequest_Put)(nil),
		(*BlobRequest_Want)(nil),
		(*BlobRequest_Get)(nil),
	}
	file_arc_blob_v1_blob_proto_msgTypes[4].OneofWrappers = []any{
		(*BlobResponse_Stored)(nil),
		(*BlobResponse_Have)(nil),
		(*BlobResponse_Redirect)(nil),
		(*BlobResponse_Data)(nil),
		(*BlobResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arc_blob_v1_blob_proto_rawDesc), len(file_arc_blob_v1_blob_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arc_blob_v1_blob_proto_goTypes,
		DependencyIndexes: file_arc_blob_v1_blob_proto_depIdxs,
		EnumInfos:         file_arc_blob_v1_blob_proto_enumTypes,
		MessageInfos:      file_arc_blob_v1_blob_proto_msgTypes,
	}.Build()
	File_arc_blob_v1_blob_proto = out.File
	file_arc_blob_v1_blob_proto_goTypes = nil
	file_arc_blob_v1_blob_proto_depIdxs = nil
}
