// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: arc/node/v1/node.proto

package nodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order int32

const (
	Order_ORDER_ASCENDING  Order = 0
	Order_ORDER_DESCENDING Order = 1
)

// Enum value maps for Order.
var (
	Order_name = map[int32]string{
		0: "ORDER_ASCENDING",
		1: "ORDER_DESCENDING",
	}
	Order_value = map[string]int32{
		"ORDER_ASCENDING":  0,
		"ORDER_DESCENDING": 1,
	}
)

func (x Order) Enum() *Order {
	p := new(Order)
	*p = x
	return p
}

func (x Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Order) Descriptor() protoreflect.EnumDescriptor {
	return file_arc_node_v1_node_proto_enumTypes[0].Descriptor()
}

func (Order) Type() protoreflect.EnumType {
	return &file_arc_node_v1_node_proto_enumTypes[0]
}

func (x Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Order.Descriptor instead.
func (Order) EnumDescriptor() ([]byte, []int) {
	return file_arc_node_v1_node_proto_rawDescGZIP(), []int{0}
}

type ResolveGetResponse_Kind int32

const (
	ResolveGetResponse_KIND_BLOB    ResolveGetResponse_Kind = 0
	ResolveGetResponse_KIND_MESSAGE ResolveGetResponse_Kind = 1
)

// Enum value maps for ResolveGetResponse_Kind.
var (
	ResolveGetResponse_Kind_name = map[int32]string{
		0: "KIND_BLOB",
		1: "KIND_MESSAGE",
	}
	ResolveGetResponse_Kind_value = map[string]int32{
		"KIND_BLOB":    0,
		"KIND_MESSAGE": 1,
	}
)

func (x ResolveGetResponse_Kind) Enum() *ResolveGetResponse_Kind {
	p := new(ResolveGetResponse_Kind)
	*p = x
	return p
}

func (x ResolveGetResponse_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResolveGetResponse_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_arc_node_v1_node_proto_enumTypes[1].Descriptor()
}

func (ResolveGetResponse_Kind) Type() protoreflect.EnumType {
	return &file_arc_node_v1_node_proto_enumTypes[1]
}

func (x ResolveGetResponse_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResolveGetResponse_Kind.Descriptor instead.
func (ResolveGetResponse_Kind) EnumDescriptor() ([]byte, []int) {
	return file_arc_node_v1_node_proto_rawDescGZIP(), []int{12, 0}
}

type PutContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutContentRequest) Reset() {
	*x = PutContentRequest{}
	mi := &file_arc_node_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutContentRequest) ProtoMessage() {}

func (x *PutContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arc_node_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutContentRequest.ProtoReflect.Descriptor instead.
func (*PutContentRequest) Descriptor() ([]byte, []int) {
	return file_arc_node_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *PutContentRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PutContentRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type PutContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     []byte                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"` // 32-byte SHA-256 hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutContentResponse) Reset() {
	*x = PutContentResponse{}
	mi := &file_arc_node_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutContentResponse) ProtoMessage() {}

func (x *PutContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arc_node_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutContentResponse.ProtoReflect.Descriptor instead.
func (*PutContentResponse) Descriptor() ([]byte, []int) {
	return file_arc_node_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *PutContentResponse) GetReference() []byte {
	if x != nil {
		return x.Reference
	}
	return nil
}

type GetContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     []byte                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"` // 32-byte SHA-256 hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRequest) Reset() {
	*x = GetContentRequest{}
	mi := &file_arc_node_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRequest) ProtoMessage() {}

func (x *GetContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arc_node_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRequest.ProtoReflect.Descriptor instead.
func (*GetContentRequest) Descriptor() ([]byte, []int) {
	return file_arc_node_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *GetContentRequest) GetReference() []byte {
	if x != nil {
		return x.Reference
	}
	return nil
}

type GetContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentResponse) Reset() {
	*x = GetContentResponse{}
	mi := &file_arc_node_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentResponse) ProtoMessage() {}

func (x *GetContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arc_node_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentResponse.ProtoReflect.Descriptor instead.
func (*GetContentResponse) Descriptor() ([]byte, []int) {
	return file_arc_node_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *GetContentResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetContentResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type IndexEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     []byte                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexEntry) Reset() {
	*x = IndexEntry{}
	mi := &file_arc_node_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexEntry) ProtoMessage() {}

func (x *IndexEntry) ProtoReflect() protoreflect.Message {
	mi := &file_arc_node_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexEntry.ProtoReflect.Descriptor instead.
func (*IndexEntry) Descriptor() ([]byte, []int) {
	return file_arc_node_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *IndexEntry) GetReference() []byte {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *IndexEntry) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *IndexEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                                                                         // canonical message bytes (from message.CanonicalBytes)
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // indexing hints
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_arc_node_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arc_node_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_arc_node_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SendMessageRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     []byte                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"` // message reference
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_arc_node_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arc_node_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_arc_node_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *SendMessageResponse) GetReference() []byte {
	if x != nil {
		return x.Reference
	}
	return nil
}

type QueryMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        map[string]string      `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Expression    string                 `protobuf:"bytes,4,opt,name=expression,proto3" json:"expression,omitempty"` // CEL filter
	Cursor        string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Order         Order                  `protobuf:"varint,6,opt,name=order,proto3,enum=arc.node.v1.Order" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMessagesRequest) Reset() {
	*x = QueryMessagesRequest{}
	mi := &file_arc_node_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMessagesRequest) ProtoMessage() {}

func (x *QueryMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arc_node_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMessagesRequest.ProtoReflect.Descriptor instead.
func (*QueryMessagesRequest) Descriptor() ([]byte, []int) {
	return file_arc_node_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *QueryMessagesRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *QueryMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryMessagesRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *QueryMessagesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *QueryMessagesRequest) GetOrder() Order {
	if x != nil {
		return x.Order
	}
	return Order_ORDER_ASCENDING
}

type QueryMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*IndexEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMessagesResponse) Reset() {
	*x = QueryMessagesResponse{}
	mi := &file_arc_node_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMessagesResponse) ProtoMessage() {}

func (x *QueryMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arc_node_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMessagesResponse.ProtoReflect.Descriptor instead.
func (*QueryMessagesResponse) Descriptor() ([]byte, []int) {
	return file_arc_node_v1_node_proto_rawDescGZIP(), []int{8}
}

func (x *QueryMessagesResponse) GetEntries() []*IndexEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *QueryMessagesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *QueryMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type SubscribeMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        map[string]string      `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Expression    string                 `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"` // CEL filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeMessagesRequest) Reset() {
	*x = SubscribeMessagesRequest{}
	mi := &file_arc_node_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeMessagesRequest) ProtoMessage() {}

func (x *SubscribeMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arc_node_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeMessagesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeMessagesRequest) Descriptor() ([]byte, []int) {
	return file_arc_node_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeMessagesRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SubscribeMessagesRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

type SubscribeMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *IndexEntry            `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeMessagesResponse) Reset() {
	*x = SubscribeMessagesResponse{}
	mi := &file_arc_node_v1_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeMessagesResponse) ProtoMessage() {}

func (x *SubscribeMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arc_node_v1_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeMessagesResponse.ProtoReflect.Descriptor instead.
func (*SubscribeMessagesResponse) Descriptor() ([]byte, []int) {
	return file_arc_node_v1_node_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeMessagesResponse) GetEntry() *IndexEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type ResolveGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"` // hex prefix (minimum 4 characters)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveGetRequest) Reset() {
	*x = ResolveGetRequest{}
	mi := &file_arc_node_v1_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveGetRequest) ProtoMessage() {}

func (x *ResolveGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arc_node_v1_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveGetRequest.ProtoReflect.Descriptor instead.
func (*ResolveGetRequest) Descriptor() ([]byte, []int) {
	return file_arc_node_v1_node_proto_rawDescGZIP(), []int{11}
}

func (x *ResolveGetRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ResolveGetResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Kind          ResolveGetResponse_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=arc.node.v1.ResolveGetResponse_Kind" json:"kind,omitempty"`
	Reference     []byte                  `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`                                                                     // full 32-byte SHA-256 reference
	Data          []byte                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                                                               // blob content (KIND_BLOB only)
	Labels        map[string]string       `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // message labels (KIND_MESSAGE only)
	Timestamp     int64                   `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                    // message timestamp (KIND_MESSAGE only)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveGetResponse) Reset() {
	*x = ResolveGetResponse{}
	mi := &file_arc_node_v1_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveGetResponse) ProtoMessage() {}

func (x *ResolveGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arc_node_v1_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveGetResponse.ProtoReflect.Descriptor instead.
func (*ResolveGetResponse) Descriptor() ([]byte, []int) {
	return file_arc_node_v1_node_proto_rawDescGZIP(), []int{12}
}

func (x *ResolveGetResponse) GetKind() ResolveGetResponse_Kind {
	if x != nil {
		return x.Kind
	}
	return ResolveGetResponse_KIND_BLOB
}

func (x *ResolveGetResponse) GetReference() []byte {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *ResolveGetResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ResolveGetResponse) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ResolveGetResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_arc_node_v1_node_proto protoreflect.FileDescriptor

const file_arc_node_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x16arc/node/v1/node.proto\x12\varc.node.v1\"J\n" +
	"\x11PutContentRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"2\n" +
	"\x12PutContentResponse\x12\x1c\n" +
	"\treference\x18\x01 \x01(\fR\treference\"1\n" +
	"\x11GetContentRequest\x12\x1c\n" +
	"\treference\x18\x01 \x01(\fR\treference\"K\n" +
	"\x12GetContentResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"\xc0\x01\n" +
	"\n" +
	"IndexEntry\x12\x1c\n" +
	"\treference\x18\x01 \x01(\fR\treference\x12;\n" +
	"\x06labels\x18\x02 \x03(\v2#.arc.node.v1.IndexEntry.LabelsEntryR\x06labels\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x01\n" +
	"\x12SendMessageRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\x12C\n" +
	"\x06labels\x18\x02 \x03(\v2+.arc.node.v1.SendMessageRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"3\n" +
	"\x13SendMessageResponse\x12\x1c\n" +
	"\treference\x18\x01 \x01(\fR\treference\"\x90\x02\n" +
	"\x14QueryMessagesRequest\x12E\n" +
	"\x06labels\x18\x01 \x03(\v2-.arc.node.v1.QueryMessagesRequest.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1e\n" +
	"\n" +
	"expression\x18\x04 \x01(\tR\n" +
	"expression\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\x12(\n" +
	"\x05order\x18\x06 \x01(\x0e2\x12.arc.node.v1.OrderR\x05order\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x01\n" +
	"\x15QueryMessagesResponse\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.arc.node.v1.IndexEntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\xc0\x01\n" +
	"\x18SubscribeMessagesRequest\x12I\n" +
	"\x06labels\x18\x01 \x03(\v21.arc.node.v1.SubscribeMessagesRequest.LabelsEntryR\x06labels\x12\x1e\n" +
	"\n" +
	"expression\x18\x02 \x01(\tR\n" +
	"expression\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"J\n" +
	"\x19SubscribeMessagesResponse\x12-\n" +
	"\x05entry\x18\x01 \x01(\v2\x17.arc.node.v1.IndexEntryR\x05entry\"+\n" +
	"\x11ResolveGetRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"\xc7\x02\n" +
	"\x12ResolveGetResponse\x128\n" +
	"\x04kind\x18\x01 \x01(\x0e2$.arc.node.v1.ResolveGetResponse.KindR\x04kind\x12\x1c\n" +
	"\treference\x18\x02 \x01(\fR\treference\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12C\n" +
	"\x06labels\x18\x04 \x03(\v2+.arc.node.v1.ResolveGetResponse.LabelsEntryR\x06labels\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"'\n" +
	"\x04Kind\x12\r\n" +
	"\tKIND_BLOB\x10\x00\x12\x10\n" +
	"\fKIND_MESSAGE\x10\x01*2\n" +
	"\x05Order\x12\x13\n" +
	"\x0fORDER_ASCENDING\x10\x00\x12\x14\n" +
	"\x10ORDER_DESCENDING\x10\x012\x8a\x04\n" +
	"\vNodeService\x12M\n" +
	"\n" +
	"PutContent\x12\x1e.arc.node.v1.PutContentRequest\x1a\x1f.arc.node.v1.PutContentResponse\x12M\n" +
	"\n" +
	"GetContent\x12\x1e.arc.node.v1.GetContentRequest\x1a\x1f.arc.node.v1.GetContentResponse\x12P\n" +
	"\vSendMessage\x12\x1f.arc.node.v1.SendMessageRequest\x1a .arc.node.v1.SendMessageResponse\x12V\n" +
	"\rQueryMessages\x12!.arc.node.v1.QueryMessagesRequest\x1a\".arc.node.v1.QueryMessagesResponse\x12d\n" +
	"\x11SubscribeMessages\x12%.arc.node.v1.SubscribeMessagesRequest\x1a&.arc.node.v1.SubscribeMessagesResponse0\x01\x12M\n" +
	"\n" +
	"ResolveGet\x12\x1e.arc.node.v1.ResolveGetRequest\x1a\x1f.arc.node.v1.ResolveGetResponseB5Z3github.com/gezibash/arc-node/api/arc/node/v1;nodev1b\x06proto3"

var (
	file_arc_node_v1_node_proto_rawDescOnce sync.Once
	file_arc_node_v1_node_proto_rawDescData []byte
)

func file_arc_node_v1_node_proto_rawDescGZIP() []byte {
	file_arc_node_v1_node_proto_rawDescOnce.Do(func() {
		file_arc_node_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arc_node_v1_node_proto_rawDesc), len(file_arc_node_v1_node_proto_rawDesc)))
	})
	return file_arc_node_v1_node_proto_rawDescData
}

var file_arc_node_v1_node_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_arc_node_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_arc_node_v1_node_proto_goTypes = []any{
	(Order)(0),                        // 0: arc.node.v1.Order
	(ResolveGetResponse_Kind)(0),      // 1: arc.node.v1.ResolveGetResponse.Kind
	(*PutContentRequest)(nil),         // 2: arc.node.v1.PutContentRequest
	(*PutContentResponse)(nil),        // 3: arc.node.v1.PutContentResponse
	(*GetContentRequest)(nil),         // 4: arc.node.v1.GetContentRequest
	(*GetContentResponse)(nil),        // 5: arc.node.v1.GetContentResponse
	(*IndexEntry)(nil),                // 6: arc.node.v1.IndexEntry
	(*SendMessageRequest)(nil),        // 7: arc.node.v1.SendMessageRequest
	(*SendMessageResponse)(nil),       // 8: arc.node.v1.SendMessageResponse
	(*QueryMessagesRequest)(nil),      // 9: arc.node.v1.QueryMessagesRequest
	(*QueryMessagesResponse)(nil),     // 10: arc.node.v1.QueryMessagesResponse
	(*SubscribeMessagesRequest)(nil),  // 11: arc.node.v1.SubscribeMessagesRequest
	(*SubscribeMessagesResponse)(nil), // 12: arc.node.v1.SubscribeMessagesResponse
	(*ResolveGetRequest)(nil),         // 13: arc.node.v1.ResolveGetRequest
	(*ResolveGetResponse)(nil),        // 14: arc.node.v1.ResolveGetResponse
	nil,                               // 15: arc.node.v1.IndexEntry.LabelsEntry
	nil,                               // 16: arc.node.v1.SendMessageRequest.LabelsEntry
	nil,                               // 17: arc.node.v1.QueryMessagesRequest.LabelsEntry
	nil,                               // 18: arc.node.v1.SubscribeMessagesRequest.LabelsEntry
	nil,                               // 19: arc.node.v1.ResolveGetResponse.LabelsEntry
}
var file_arc_node_v1_node_proto_depIdxs = []int32{
	15, // 0: arc.node.v1.IndexEntry.labels:type_name -> arc.node.v1.IndexEntry.LabelsEntry
	16, // 1: arc.node.v1.SendMessageRequest.labels:type_name -> arc.node.v1.SendMessageRequest.LabelsEntry
	17, // 2: arc.node.v1.QueryMessagesRequest.labels:type_name -> arc.node.v1.QueryMessagesRequest.LabelsEntry
	0,  // 3: arc.node.v1.QueryMessagesRequest.order:type_name -> arc.node.v1.Order
	6,  // 4: arc.node.v1.QueryMessagesResponse.entries:type_name -> arc.node.v1.IndexEntry
	18, // 5: arc.node.v1.SubscribeMessagesRequest.labels:type_name -> arc.node.v1.SubscribeMessagesRequest.LabelsEntry
	6,  // 6: arc.node.v1.SubscribeMessagesResponse.entry:type_name -> arc.node.v1.IndexEntry
	1,  // 7: arc.node.v1.ResolveGetResponse.kind:type_name -> arc.node.v1.ResolveGetResponse.Kind
	19, // 8: arc.node.v1.ResolveGetResponse.labels:type_name -> arc.node.v1.ResolveGetResponse.LabelsEntry
	2,  // 9: arc.node.v1.NodeService.PutContent:input_type -> arc.node.v1.PutContentRequest
	4,  // 10: arc.node.v1.NodeService.GetContent:input_type -> arc.node.v1.GetContentRequest
	7,  // 11: arc.node.v1.NodeService.SendMessage:input_type -> arc.node.v1.SendMessageRequest
	9,  // 12: arc.node.v1.NodeService.QueryMessages:input_type -> arc.node.v1.QueryMessagesRequest
	11, // 13: arc.node.v1.NodeService.SubscribeMessages:input_type -> arc.node.v1.SubscribeMessagesRequest
	13, // 14: arc.node.v1.NodeService.ResolveGet:input_type -> arc.node.v1.ResolveGetRequest
	3,  // 15: arc.node.v1.NodeService.PutContent:output_type -> arc.node.v1.PutContentResponse
	5,  // 16: arc.node.v1.NodeService.GetContent:output_type -> arc.node.v1.GetContentResponse
	8,  // 17: arc.node.v1.NodeService.SendMessage:output_type -> arc.node.v1.SendMessageResponse
	10, // 18: arc.node.v1.NodeService.QueryMessages:output_type -> arc.node.v1.QueryMessagesResponse
	12, // 19: arc.node.v1.NodeService.SubscribeMessages:output_type -> arc.node.v1.SubscribeMessagesResponse
	14, // 20: arc.node.v1.NodeService.ResolveGet:output_type -> arc.node.v1.ResolveGetResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_arc_node_v1_node_proto_init() }
func file_arc_node_v1_node_proto_init() {
	if File_arc_node_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arc_node_v1_node_proto_rawDesc), len(file_arc_node_v1_node_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arc_node_v1_node_proto_goTypes,
		DependencyIndexes: file_arc_node_v1_node_proto_depIdxs,
		EnumInfos:         file_arc_node_v1_node_proto_enumTypes,
		MessageInfos:      file_arc_node_v1_node_proto_msgTypes,
	}.Build()
	File_arc_node_v1_node_proto = out.File
	file_arc_node_v1_node_proto_goTypes = nil
	file_arc_node_v1_node_proto_depIdxs = nil
}
