// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: arc/node/v1/node.proto

package nodev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_PutContent_FullMethodName        = "/arc.node.v1.NodeService/PutContent"
	NodeService_GetContent_FullMethodName        = "/arc.node.v1.NodeService/GetContent"
	NodeService_SendMessage_FullMethodName       = "/arc.node.v1.NodeService/SendMessage"
	NodeService_QueryMessages_FullMethodName     = "/arc.node.v1.NodeService/QueryMessages"
	NodeService_SubscribeMessages_FullMethodName = "/arc.node.v1.NodeService/SubscribeMessages"
	NodeService_Federate_FullMethodName          = "/arc.node.v1.NodeService/Federate"
	NodeService_ListPeers_FullMethodName         = "/arc.node.v1.NodeService/ListPeers"
	NodeService_ResolveGet_FullMethodName        = "/arc.node.v1.NodeService/ResolveGet"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	// Content storage
	PutContent(ctx context.Context, in *PutContentRequest, opts ...grpc.CallOption) (*PutContentResponse, error)
	GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error)
	// Messaging
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	QueryMessages(ctx context.Context, in *QueryMessagesRequest, opts ...grpc.CallOption) (*QueryMessagesResponse, error)
	SubscribeMessages(ctx context.Context, in *SubscribeMessagesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeMessagesResponse], error)
	Federate(ctx context.Context, in *FederateRequest, opts ...grpc.CallOption) (*FederateResponse, error)
	ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error)
	// Unified get: resolve prefix against blobs and messages
	ResolveGet(ctx context.Context, in *ResolveGetRequest, opts ...grpc.CallOption) (*ResolveGetResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) PutContent(ctx context.Context, in *PutContentRequest, opts ...grpc.CallOption) (*PutContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutContentResponse)
	err := c.cc.Invoke(ctx, NodeService_PutContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentResponse)
	err := c.cc.Invoke(ctx, NodeService_GetContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, NodeService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) QueryMessages(ctx context.Context, in *QueryMessagesRequest, opts ...grpc.CallOption) (*QueryMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryMessagesResponse)
	err := c.cc.Invoke(ctx, NodeService_QueryMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SubscribeMessages(ctx context.Context, in *SubscribeMessagesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeMessagesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], NodeService_SubscribeMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeMessagesRequest, SubscribeMessagesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_SubscribeMessagesClient = grpc.ServerStreamingClient[SubscribeMessagesResponse]

func (c *nodeServiceClient) Federate(ctx context.Context, in *FederateRequest, opts ...grpc.CallOption) (*FederateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FederateResponse)
	err := c.cc.Invoke(ctx, NodeService_Federate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPeersResponse)
	err := c.cc.Invoke(ctx, NodeService_ListPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ResolveGet(ctx context.Context, in *ResolveGetRequest, opts ...grpc.CallOption) (*ResolveGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveGetResponse)
	err := c.cc.Invoke(ctx, NodeService_ResolveGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
type NodeServiceServer interface {
	// Content storage
	PutContent(context.Context, *PutContentRequest) (*PutContentResponse, error)
	GetContent(context.Context, *GetContentRequest) (*GetContentResponse, error)
	// Messaging
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	QueryMessages(context.Context, *QueryMessagesRequest) (*QueryMessagesResponse, error)
	SubscribeMessages(*SubscribeMessagesRequest, grpc.ServerStreamingServer[SubscribeMessagesResponse]) error
	Federate(context.Context, *FederateRequest) (*FederateResponse, error)
	ListPeers(context.Context, *ListPeersRequest) (*ListPeersResponse, error)
	// Unified get: resolve prefix against blobs and messages
	ResolveGet(context.Context, *ResolveGetRequest) (*ResolveGetResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) PutContent(context.Context, *PutContentRequest) (*PutContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutContent not implemented")
}
func (UnimplementedNodeServiceServer) GetContent(context.Context, *GetContentRequest) (*GetContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContent not implemented")
}
func (UnimplementedNodeServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedNodeServiceServer) QueryMessages(context.Context, *QueryMessagesRequest) (*QueryMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryMessages not implemented")
}
func (UnimplementedNodeServiceServer) SubscribeMessages(*SubscribeMessagesRequest, grpc.ServerStreamingServer[SubscribeMessagesResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeMessages not implemented")
}
func (UnimplementedNodeServiceServer) Federate(context.Context, *FederateRequest) (*FederateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Federate not implemented")
}
func (UnimplementedNodeServiceServer) ListPeers(context.Context, *ListPeersRequest) (*ListPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPeers not implemented")
}
func (UnimplementedNodeServiceServer) ResolveGet(context.Context, *ResolveGetRequest) (*ResolveGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveGet not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_PutContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).PutContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_PutContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).PutContent(ctx, req.(*PutContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetContent(ctx, req.(*GetContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_QueryMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).QueryMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_QueryMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).QueryMessages(ctx, req.(*QueryMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SubscribeMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeMessagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).SubscribeMessages(m, &grpc.GenericServerStream[SubscribeMessagesRequest, SubscribeMessagesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_SubscribeMessagesServer = grpc.ServerStreamingServer[SubscribeMessagesResponse]

func _NodeService_Federate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FederateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Federate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Federate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Federate(ctx, req.(*FederateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ListPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListPeers(ctx, req.(*ListPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ResolveGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ResolveGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ResolveGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ResolveGet(ctx, req.(*ResolveGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arc.node.v1.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutContent",
			Handler:    _NodeService_PutContent_Handler,
		},
		{
			MethodName: "GetContent",
			Handler:    _NodeService_GetContent_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _NodeService_SendMessage_Handler,
		},
		{
			MethodName: "QueryMessages",
			Handler:    _NodeService_QueryMessages_Handler,
		},
		{
			MethodName: "Federate",
			Handler:    _NodeService_Federate_Handler,
		},
		{
			MethodName: "ListPeers",
			Handler:    _NodeService_ListPeers_Handler,
		},
		{
			MethodName: "ResolveGet",
			Handler:    _NodeService_ResolveGet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeMessages",
			Handler:       _NodeService_SubscribeMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "arc/node/v1/node.proto",
}
